#!/bin/bash

#SBATCH --job-name=array
#SBATCH --array=480              #Array job indices/range for $SLURM_ARRAY_TASK_ID (can be incremented if desired)
#SBATCH --time=24:00:00
#SBATCH --partition=high_mem
#SBATCH --ntasks=1
#SBATCH --mem=4G
#SBATCH --error=array_%A_%a.err   #Error file label by job number and index.

# Print the task id.
echo "My SLURM_ARRAY_TASK_ID: " $SLURM_ARRAY_TASK_ID > test_"$SLURM_ARRAY_TASK_ID"


cd $SLURM_SUBMIT_DIR

module use /opt/software/user-pkgs/modulefiles/all
module use /opt/software/user-pkgs/modulefiles/psychology
module load setcondaenv

conda info -e

module load amica
module load matlab/2021a

matlab -nosplash -nodesktop -nodisplay -r "run('/users/nemo/projects/Airforce/paper/preprocessing/C_ICA_af_array($SLURM_ARRAY_TASK_ID)');exit"




