---
title: "duration stats"
output: html_notebook
---

# 1. Import functions
```{r}
library(devtools)
library(lmerTest)
library(lme4)
library(emmeans)
library(tidyverse)
library(broom)
library(kableExtra)
library(ggpubr)
library(ggprism)
library(modelbased)
```
# 2. Load dataset for absolute duration/common sleep duration (Fig 1, S1)
```{r}
df_week <- read_csv("duration_allnight_07-Dec-2025.csv", show_col_types = FALSE)
df_commonweek <- read_csv("duration_common_07-Dec-2025.csv", show_col_types = FALSE)

# Factorise
cols <- c("participant", "condition", "night", "order")
df_week <- df_week %>% mutate_at(cols, factor)
df_commonweek <- df_commonweek %>% mutate_at(cols, factor)

# Remove Night 9 (recov)
df_week <- df_week %>% 
  filter(!night == "9")
df_commonweek <- df_commonweek %>% 
  filter(!night == "9")

```
# 3. Run lmes
```{r}
## absolute duration ----
# tst
fit.allnight_tst <- lmer(tst_min ~ night + night:condition + baseline_tstmin + order + (1|participant), data=df_week)
anova.tst <- anova(fit.allnight_tst)
tst.esmmeans <- estimate_means(fit.allnight_tst,  by = c("night", "condition"))

#res <- residuals(fit.allnight_tst)
#qqnorm(res); qqline(res, col="red")

# REM 
fit.allnight_REM <- lmer(REM_min ~ night + night:condition + baseline_REMmin + order + (1|participant), data=df_week)
anova.REM <- anova(fit.allnight_REM)
REM.esmmeans <- estimate_means(fit.allnight_REM,  by = c("night", "condition"))

#res <- residuals(fit.allnight_REM)
#qqnorm(res); qqline(res, col="red")

# phasic 
fit.allnight_phasic <- lmer(phasic_min ~ night + night:condition + baseline_phasicmin + order +(1|participant), data=df_week)
anova.phasic <- anova(fit.allnight_phasic)
phasic.esmmeans <- estimate_means(fit.allnight_phasic, by = c("night", "condition"))

# tonic 
fit.allnight_tonic <- lmer(tonic_min ~ night + night:condition + baseline_tonicmin + order +(1|participant), data=df_week)
anova.tonic <- anova(fit.allnight_tonic)
tonic.esmmeans <- estimate_means(fit.allnight_tonic, by = c("night", "condition"))

# NREM
fit.allnight_NREM <- lmer(NREM_min ~ night + night:condition + baseline_NREMmin + order +(1|participant), data=df_week)
anova.NREM <- anova(fit.allnight_NREM)
NREM.esmmeans <- estimate_means(fit.allnight_NREM, by = c("night", "condition"))

fit.allnight_N1 <- lmer(N1_min ~ night + night:condition + baseline_N1min + order +(1|participant), data=df_week)
anova.N1 <- anova(fit.allnight_N1)
N1.esmmeans <- estimate_means(fit.allnight_N1, by = c("night", "condition"))

fit.allnight_N2 <- lmer(N2_min ~ night + night:condition + baseline_N2min + order +(1|participant), data=df_week)
anova.N2 <- anova(fit.allnight_N2)
N2.esmmeans <- estimate_means(fit.allnight_N2, by = c("night", "condition"))

fit.allnight_N3 <- lmer(N3_min ~ night + night:condition + baseline_N3min + order +(1|participant), data=df_week)
anova.N3 <- anova(fit.allnight_N3)
N3.esmmeans <- estimate_means(fit.allnight_N3, by = c("night", "condition"))

# wake
fit.allnight_wake <- lmer(WASO_min ~ night + night:condition + baseline_wakemin + order +(1|participant), data=df_week)
anova.wake<- anova(fit.allnight_wake)
wake.esmmeans <- estimate_means(fit.allnight_wake, by = c("night", "condition"))

## percentage per tst ----
# REM 
fit.allnight_REMperc <- lmer(REM_perc ~ night + night:condition + baseline_REMperc + order + (1|participant), data=df_week)
anova.REMperc <- anova(fit.allnight_REMperc)
REMperc.esmmeans <- estimate_means(fit.allnight_REMperc,  by = c("night", "condition"))

# phasic (per tst or per REM)
fit.allnight_phasicperc <- lmer(phasic_perc ~ night + night:condition + baseline_phasicperc + order +(1|participant), data=df_week)
anova.phasicperc <- anova(fit.allnight_phasicperc)
phasicperc.esmmeans <- estimate_means(fit.allnight_phasicperc, by = c("night", "condition"))

fit.allnight_phasicpercREM <- lmer(phasicperREM_perc ~ night + night:condition + baseline_phasicperREMperc + order +(1|participant), data=df_week)
anova.phasicperREMperc <- anova(fit.allnight_phasicpercREM)
phasicperREMperc.esmmeans <- estimate_means(fit.allnight_phasicpercREM, by = c("night", "condition"))

# tonic (per tst or per REM)
fit.allnight_tonicperc <- lmer(tonic_perc ~ night + night:condition + baseline_tonicperc + order +(1|participant), data=df_week)
anova.tonicperc <- anova(fit.allnight_tonicperc)
tonicperc.esmmeans <- estimate_means(fit.allnight_tonicperc, by = c("night", "condition"))

fit.allnight_tonicpercREM <- lmer(tonicperREM_perc ~ night + night:condition + baseline_tonicperREMperc + order +(1|participant), data=df_week)
anova.tonicperREMperc <- anova(fit.allnight_tonicpercREM)
tonicperREMperc.esmmeans <- estimate_means(fit.allnight_tonicpercREM, by = c("night", "condition"))

# N1
fit.allnight_N1perc <- lmer(N1_perc ~ night + night:condition + baseline_N1perc + order +(1|participant), data=df_week)
anova.N1perc <- anova(fit.allnight_N1perc)
N1perc.esmmeans <- estimate_means(fit.allnight_N1perc, by = c("night", "condition"))

# N2
fit.allnight_N2perc <- lmer(N2_perc ~ night + night:condition + baseline_N2perc + order +(1|participant), data=df_week)
anova.N2perc <- anova(fit.allnight_N2perc)
N2perc.esmmeans <- estimate_means(fit.allnight_N2perc, by = c("night", "condition"))

# N3
fit.allnight_N3perc <- lmer(N3_perc ~ night + night:condition + baseline_N3perc + order +(1|participant), data=df_week)
anova.N3perc <- anova(fit.allnight_N3perc)
N3perc.esmmeans <- estimate_means(fit.allnight_N3perc, by = c("night", "condition"))

# NREM
fit.allnight_NREMperc <- lmer(NREM_perc ~ night + night:condition + baseline_NREMperc + order +(1|participant), data=df_week)
anova.NREMperc <- anova(fit.allnight_NREMperc)
NREMperc.esmmeans <- estimate_means(fit.allnight_NREMperc, by = c("night", "condition"))

# wake
fit.allnight_wakeperc <- lmer(wake_perc ~ night + night:condition  + baseline_wakeperc + order +(1|participant), data=df_week)
anova.wakeperc <- anova(fit.allnight_wakeperc)
wakeperc.esmmeans <- estimate_means(fit.allnight_wakeperc, by = c("night", "condition"))

## percentage per common sleep duration ----
# REM 
fit.common_REMperc <- lmer(common_REM_perc ~ night + night:condition + baseline_common_REMperc + order + (1|participant), data=df_commonweek)
anova.commonREMperc <- anova(fit.common_REMperc)
common_REMperc.esmmeans <- estimate_means(fit.common_REMperc,  by = c("night", "condition"))

# phasic 
fit.common_phasicperc <- lmer(common_phasic_perc ~ night + night:condition + baseline_common_phasicperc + order +(1|participant), data=df_commonweek)
anova.commonphasicperc <- anova(fit.common_phasicperc)
common_phasicperc.esmmeans <- estimate_means(fit.common_phasicperc, by = c("night", "condition"))

# tonic 
fit.common_tonicperc <- lmer(common_tonic_perc ~ night + night:condition + baseline_common_tonicperc + order +(1|participant), data=df_commonweek)
anova.commontonicperc <- anova(fit.common_tonicperc)
common_tonicperc.esmmeans <- estimate_means(fit.common_tonicperc, by = c("night", "condition"))

# N1
fit.common_N1perc <- lmer(common_N1_perc ~ night + night:condition + baseline_common_N1perc + order + (1|participant), data=df_commonweek)
anova.N1perc <- anova(fit.common_N1perc)
common_N1perc.esmmeans <- estimate_means(fit.common_N1perc, by = c("night", "condition"))

# N2
fit.common_N2perc <- lmer(common_N2_perc ~ night + night:condition + baseline_common_N2perc + order +(1|participant), data=df_commonweek)
anova.commonN2perc <- anova(fit.common_N2perc)
common_N2perc.esmmeans <- estimate_means(fit.common_N2perc, by = c("night", "condition"))

# N3
fit.common_N3perc <- lmer(common_N3_perc ~ night + night:condition + baseline_common_N3perc + order +(1|participant), data=df_commonweek)
anova.commonN3perc <- anova(fit.common_N3perc)
common_N3perc.esmmeans <- estimate_means(fit.common_N3perc, by = c("night", "condition"))

# NREM
fit.common_NREMperc <- lmer(common_NREM_perc ~ night + night:condition + baseline_common_NREMperc + order +(1|participant), data=df_commonweek)
anova.commonNREMperc <- anova(fit.common_NREMperc)
common_NREMperc.esmmeans <- estimate_means(fit.common_NREMperc, by = c("night", "condition"))

# wake
fit.common_wakeperc <- lmer(common_wake_perc ~ night + night:condition  + baseline_common_wakeperc + order +(1|participant), data=df_commonweek)
anova.commonwakeperc <- anova(fit.common_wakeperc)
common_wakeperc.esmmeans <- estimate_means(fit.common_wakeperc, by = c("night", "condition"))
```
# 4. Posthoc 
```{r}
# duration ----
#Perform contrasts comparing condition for each night

#REM
pairs(emmeans(fit.allnight_REM, ~night:condition, by="night", p.adjust = "tukey"))

#phasic
pairs(emmeans(fit.allnight_phasic, ~night:condition, by="night", p.adjust = "tukey"))

#tonic
pairs(emmeans(fit.allnight_tonic, ~night:condition, by="night", p.adjust = "tukey"))

#TST
pairs(emmeans(fit.allnight_tst, ~night:condition, by="night", p.adjust = "tukey"))

#WASO
pairs(emmeans(fit.allnight_wake, ~night:condition, by="night", p.adjust = "tukey"))

#NREM
pairs(emmeans(fit.allnight_NREM, ~night:condition, by="night", p.adjust = "tukey"))

#N1
pairs(emmeans(fit.allnight_N1, ~night:condition, by="night", p.adjust = "tukey"))

#N2
pairs(emmeans(fit.allnight_N2, ~night:condition, by="night", p.adjust = "tukey"))

#N3
pairs(emmeans(fit.allnight_N3, ~night:condition, by="night", p.adjust = "tukey"))

# percentage per tst ----
#Perform contrasts comparing condition for each night

#REM
pairs(emmeans(fit.allnight_REMperc, ~night:condition, by="night", p.adjust = "tukey"))

#phasic
pairs(emmeans(fit.allnight_phasicperc, ~night:condition, by="night", p.adjust = "tukey"))

#tonic
pairs(emmeans(fit.allnight_tonicperc, ~night:condition, by="night", p.adjust = "tukey"))

#WASO
pairs(emmeans(fit.allnight_wakeperc, ~night:condition, by="night", p.adjust = "tukey"))

#NREM
pairs(emmeans(fit.allnight_NREMperc, ~night:condition, by="night", p.adjust = "tukey"))

#N1
pairs(emmeans(fit.allnight_N1perc, ~night:condition, by="night", p.adjust = "tukey"))

#N2
pairs(emmeans(fit.allnight_N2perc, ~night:condition, by="night", p.adjust = "tukey"))

#N3
pairs(emmeans(fit.allnight_N3perc, ~night:condition, by="night", p.adjust = "tukey"))


# percentage per common sleep duration ----
#Perform contrasts comparing condition for each night

#REM
pairs(emmeans(fit.common_REMperc, ~night:condition, by="night", p.adjust = "tukey"))

#phasic
pairs(emmeans(fit.common_phasicperc, ~night:condition, by="night", p.adjust = "tukey"))

#tonic
pairs(emmeans(fit.common_tonicperc, ~night:condition, by="night", p.adjust = "tukey"))

#WASO
pairs(emmeans(fit.common_wakeperc, ~night:condition, by="night", p.adjust = "tukey"))

#NREM
pairs(emmeans(fit.common_NREMperc, ~night:condition, by="night", p.adjust = "tukey"))

#N1
pairs(emmeans(fit.common_N1perc, ~night:condition, by="night", p.adjust = "tukey"))

#N2
pairs(emmeans(fit.common_N2perc, ~night:condition, by="night", p.adjust = "tukey"))

#N3
pairs(emmeans(fit.common_N3perc, ~night:condition, by="night", p.adjust = "tukey"))


# percentage per REM ----
#Perform contrasts comparing condition for each night

#phasic
pairs(emmeans(fit.allnight_phasicpercREM, ~night:condition, by="night", p.adjust = "tukey"))

#tonic
pairs(emmeans(fit.allnight_tonicpercREM, ~night:condition, by="night", p.adjust = "tukey"))

```
# 5. Plot estimated means
```{r}
# duration
REM <- ggplot(REM.esmmeans, aes(x = night, y = Mean, group=condition, shape=condition)) +
  scale_shape_manual(values = c(16,21)) + 
  geom_line(linewidth=0.3, position =   position_nudge(0.1)) +
  geom_errorbar(aes(x=night, y=Mean, ymin=Mean-SE, ymax=Mean+SE,), width=0.4, lwd=0.3, position = position_nudge(0.1)) +
  geom_point(data = subset(REM.esmmeans, condition == "SE"), aes(shape = condition), position = position_nudge(0.1), size=2) +
  geom_point(data = subset(REM.esmmeans, condition == "SR"), aes(shape = condition), fill="white", position = position_nudge(0.1), size=2) + 
  labs(x = "night", y = "minutes") + ggtitle("REM") +
  scale_y_continuous(limits = c(60, 160), breaks = seq(60, 160, 20), expand = c(0, NA))+
 # scale_y_continuous(limits = c(15, 30), breaks = seq(15, 30, 5), expand = c(0, NA))+
  scale_x_discrete(labels=c("B", "1", "2", "3", "4", "5", "6", "7")) +
  theme_prism(base_size = 9, base_fontface="plain", base_line_size=0.2) 
REM

 phasic <- ggplot(phasic.esmmeans, aes(x = night, y = Mean, group=condition, shape=condition)) +
  scale_shape_manual(values = c(16,21)) + 
  geom_line(linewidth=0.3, position =   position_nudge(0.1), colour="#0072B2") +
  geom_errorbar(aes(x=night, y=Mean, ymin=Mean-SE, ymax=Mean+SE,), colour="#0072B2", width=0.4, lwd=0.3, position = position_nudge(0.1)) +
  geom_point(data = subset(phasic.esmmeans, condition == "SE"), aes(shape = condition), colour="#0072B2", position = position_nudge(0.1), size=2) +
  geom_point(data = subset(phasic.esmmeans, condition == "SR"), aes(shape = condition), colour="#0072B2",fill="white", position = position_nudge(0.1), size=2) + 
  labs(x = "night", y = "minutes") + ggtitle("phasic") +
  scale_y_continuous(limits = c(0, 20), breaks = seq(0, 20, 5), expand = c(0, NA))+
   # scale_y_continuous(limits = c(0, 4), breaks = seq(0, 4, 0.5), expand = c(0, NA))+
  scale_x_discrete(labels=c("B", "1", "2", "3", "4", "5", "6", "7")) +
  theme_prism(base_size = 9, base_fontface="plain", base_line_size=0.2) 
 phasic
 
tonic <- ggplot(tonic.esmmeans, aes(x = night, y = Mean, group=condition, shape=condition)) +
  scale_shape_manual(values = c(16,21)) + 
  geom_line(linewidth=0.3, position =   position_nudge(0.1), colour="#D55E00") +
  geom_errorbar(aes(x=night, y=Mean, ymin=Mean-SE, ymax=Mean+SE,), colour="#D55E00", width=0.4, lwd=0.3, position = position_nudge(0.1)) +
  geom_point(data = subset(tonic.esmmeans, condition == "SE"), aes(shape = condition), colour="#D55E00", position = position_nudge(0.1), size=2) +
  geom_point(data = subset(tonic.esmmeans, condition == "SR"), aes(shape = condition), colour="#D55E00",fill="white", position = position_nudge(0.1), size=2) + 
  labs(x = "night", y = "minutes") + ggtitle("tonic") +
  scale_y_continuous(limits = c(60, 160), breaks = seq(60, 160, 20), expand = c(0, NA))+
  scale_x_discrete(labels=c("B", "1", "2", "3", "4", "5", "6", "7")) +
  theme_prism(base_size = 9, base_fontface="plain", base_line_size=0.2) 
tonic

tst <- ggplot(tst.esmmeans, aes(x = night, y = Mean, group=condition, shape=condition)) +
  scale_shape_manual(values = c(16,21)) + 
  geom_line(linewidth=0.3, position =   position_nudge(0.1)) +
  geom_errorbar(aes(x=night, y=Mean, ymin=Mean-SE, ymax=Mean+SE,), width=0.4, lwd=0.3, position = position_nudge(0.1)) +
  geom_point(data = subset(tst.esmmeans, condition == "SE"), aes(shape = condition), position = position_nudge(0.1), size=2) +
  geom_point(data = subset(tst.esmmeans, condition == "SR"), aes(shape = condition), fill="white", position = position_nudge(0.1), size=2) + 
  labs(x = "night", y = "minutes") + ggtitle("tst") +
  scale_y_continuous(limits = c(320, 570), breaks = seq(320, 570, 50), expand = c(0, NA))+
 # scale_y_continuous(limits = c(15, 30), breaks = seq(15, 30, 5), expand = c(0, NA))+
  scale_x_discrete(labels=c("B", "1", "2", "3", "4", "5", "6", "7")) +
  theme_prism(base_size = 9, base_fontface="plain", base_line_size=0.2) 
tst

WASO <- ggplot(wake.esmmeans, aes(x = night, y = Mean, group=condition, shape=condition)) +
  scale_shape_manual(values = c(16,21)) + 
  geom_line(linewidth=0.3, position =   position_nudge(0.1)) +
  geom_errorbar(aes(x=night, y=Mean, ymin=Mean-SE, ymax=Mean+SE,), width=0.4, lwd=0.3, position = position_nudge(0.1)) +
  geom_point(data = subset(wake.esmmeans, condition == "SE"), aes(shape = condition), position = position_nudge(0.1), size=2) +
  geom_point(data = subset(wake.esmmeans, condition == "SR"), aes(shape = condition), fill="white", position = position_nudge(0.1), size=2) + 
  labs(x = "night", y = "minutes") + ggtitle("WASO") +
  scale_y_continuous(limits = c(-10, 110), breaks = seq(-10, 110, 20), expand = c(0, NA))+
 # scale_y_continuous(limits = c(15, 30), breaks = seq(15, 30, 5), expand = c(0, NA))+
  scale_x_discrete(labels=c("B", "1", "2", "3", "4", "5", "6", "7")) +
  theme_prism(base_size = 9, base_fontface="plain", base_line_size=0.2) 
WASO


NREM <- ggplot(NREM.esmmeans, aes(x = night, y = Mean, group=condition, shape=condition)) +
  scale_shape_manual(values = c(16,21)) + 
  geom_line(linewidth=0.3, position =   position_nudge(0.1)) +
  geom_errorbar(aes(x=night, y=Mean, ymin=Mean-SE, ymax=Mean+SE,), width=0.4, lwd=0.3, position = position_nudge(0.1)) +
  geom_point(data = subset(NREM.esmmeans, condition == "SE"), aes(shape = condition), position = position_nudge(0.1), size=2) +
  geom_point(data = subset(NREM.esmmeans, condition == "SR"), aes(shape = condition), fill="white", position = position_nudge(0.1), size=2) + 
  labs(x = "night", y = "minutes") + ggtitle("NREM (N2+N3)") +
  scale_y_continuous(limits = c(200, 350), breaks = seq(200, 350, 50), expand = c(0, NA))+
 # scale_y_continuous(limits = c(15, 30), breaks = seq(15, 30, 5), expand = c(0, NA))+
  scale_x_discrete(labels=c("B", "1", "2", "3", "4", "5", "6", "7")) +
  theme_prism(base_size = 9, base_fontface="plain", base_line_size=0.2) 
NREM


N1 <- ggplot(N1.esmmeans, aes(x = night, y = Mean, group=condition, shape=condition)) +
  scale_shape_manual(values = c(16,21)) + 
  geom_line(linewidth=0.3, position =   position_nudge(0.1)) +
  geom_errorbar(aes(x=night, y=Mean, ymin=Mean-SE, ymax=Mean+SE,), width=0.4, lwd=0.3, position = position_nudge(0.1)) +
  geom_point(data = subset(N1.esmmeans, condition == "SE"), aes(shape = condition), position = position_nudge(0.1), size=2) +
  geom_point(data = subset(N1.esmmeans, condition == "SR"), aes(shape = condition), fill="white", position = position_nudge(0.1), size=2) + 
  labs(x = "night", y = "minutes") + ggtitle("N1") +
  scale_y_continuous(limits = c(0, 80), breaks = seq(0, 80, 10), expand = c(0, NA))+
 # scale_y_continuous(limits = c(15, 30), breaks = seq(15, 30, 5), expand = c(0, NA))+
  scale_x_discrete(labels=c("B", "1", "2", "3", "4", "5", "6", "7")) +
  theme_prism(base_size = 9, base_fontface="plain", base_line_size=0.2) 
N1


N2 <- ggplot(N2.esmmeans, aes(x = night, y = Mean, group=condition, shape=condition)) +
  scale_shape_manual(values = c(16,21)) + 
  geom_line(linewidth=0.3, position =   position_nudge(0.1)) +
  geom_errorbar(aes(x=night, y=Mean, ymin=Mean-SE, ymax=Mean+SE,), width=0.4, lwd=0.3, position = position_nudge(0.1)) +
  geom_point(data = subset(N2.esmmeans, condition == "SE"), aes(shape = condition), position = position_nudge(0.1), size=2) +
  geom_point(data = subset(N2.esmmeans, condition == "SR"), aes(shape = condition), fill="white", position = position_nudge(0.1), size=2) + 
  labs(x = "night", y = "minutes") + ggtitle("N2") +
  scale_y_continuous(limits = c(60, 240), breaks = seq(60, 240, 30), expand = c(0, NA))+
 # scale_y_continuous(limits = c(15, 30), breaks = seq(15, 30, 5), expand = c(0, NA))+
  scale_x_discrete(labels=c("B", "1", "2", "3", "4", "5", "6", "7")) +
  theme_prism(base_size = 9, base_fontface="plain", base_line_size=0.2) 
N2


N3 <- ggplot(N3.esmmeans, aes(x = night, y = Mean, group=condition, shape=condition)) +
  scale_shape_manual(values = c(16,21)) + 
  geom_line(linewidth=0.3, position =   position_nudge(0.1)) +
  geom_errorbar(aes(x=night, y=Mean, ymin=Mean-SE, ymax=Mean+SE,), width=0.4, lwd=0.3, position = position_nudge(0.1)) +
  geom_point(data = subset(N3.esmmeans, condition == "SE"), aes(shape = condition), position = position_nudge(0.1), size=2) +
  geom_point(data = subset(N3.esmmeans, condition == "SR"), aes(shape = condition), fill="white", position = position_nudge(0.1), size=2) + 
  labs(x = "night", y = "minutes") + ggtitle("N3") +
  scale_y_continuous(limits = c(60, 120), breaks = seq(60, 120, 20), expand = c(0, NA))+
 # scale_y_continuous(limits = c(15, 30), breaks = seq(15, 30, 5), expand = c(0, NA))+
  scale_x_discrete(labels=c("B", "1", "2", "3", "4", "5", "6", "7")) +
  theme_prism(base_size = 9, base_fontface="plain", base_line_size=0.2) 
N3


# percentage per tst
REMperc <- ggplot(REMperc.esmmeans, aes(x = night, y = Mean, group=condition, shape=condition)) +
  scale_shape_manual(values = c(16,21)) + 
  geom_line(linewidth=0.3, position =   position_nudge(0.1)) +
  geom_errorbar(aes(x=night, y=Mean, ymin=Mean-SE, ymax=Mean+SE,), width=0.4, lwd=0.3, position = position_nudge(0.1)) +
  geom_point(data = subset(REMperc.esmmeans, condition == "SE"), aes(shape = condition), position = position_nudge(0.1), size=2) +
  geom_point(data = subset(REMperc.esmmeans, condition == "SR"), aes(shape = condition), fill="white", position = position_nudge(0.1), size=2) + 
  labs(x = "night", y = "% per total sleep time") + ggtitle("REM") +
  scale_y_continuous(limits = c(15, 30), breaks = seq(15, 30, 5), expand = c(0, NA))+
 # scale_y_continuous(limits = c(15, 30), breaks = seq(15, 30, 5), expand = c(0, NA))+
  scale_x_discrete(labels=c("B", "1", "2", "3", "4", "5", "6", "7")) +
  theme_prism(base_size = 9, base_fontface="plain", base_line_size=0.2) 
REMperc

phasicperc <- ggplot(phasicperc.esmmeans, aes(x = night, y = Mean, group=condition, shape=condition)) +
  scale_shape_manual(values = c(16,21)) + 
  geom_line(linewidth=0.3, position =   position_nudge(0.1), colour="#0072B2") +
  geom_errorbar(aes(x=night, y=Mean, ymin=Mean-SE, ymax=Mean+SE,), colour="#0072B2", width=0.4, lwd=0.3, position = position_nudge(0.1)) +
  geom_point(data = subset(phasicperc.esmmeans, condition == "SE"), aes(shape = condition), colour="#0072B2", position = position_nudge(0.1), size=2) +
  geom_point(data = subset(phasicperc.esmmeans, condition == "SR"), aes(shape = condition), colour="#0072B2", fill="white", position = position_nudge(0.1), size=2) + 
  labs(x = "night", y = "% per total sleep time") + ggtitle("phasic") +
  scale_y_continuous(limits = c(0, 4), breaks = seq(0, 4, 0.5), expand = c(0, NA))+
 # scale_y_continuous(limits = c(15, 30), breaks = seq(15, 30, 5), expand = c(0, NA))+
  scale_x_discrete(labels=c("B", "1", "2", "3", "4", "5", "6", "7")) +
  theme_prism(base_size = 9, base_fontface="plain", base_line_size=0.2) 
phasicperc
 
tonicperc <- ggplot(tonicperc.esmmeans, aes(x = night, y = Mean, group=condition, shape=condition)) +
  scale_shape_manual(values = c(16,21)) + 
  geom_line(linewidth=0.3, position =   position_nudge(0.1), colour="#D55E00") +
  geom_errorbar(aes(x=night, y=Mean, ymin=Mean-SE, ymax=Mean+SE,), colour="#D55E00", width=0.4, lwd=0.3, position = position_nudge(0.1)) +
  geom_point(data = subset(tonicperc.esmmeans, condition == "SE"), aes(shape = condition), colour="#D55E00", position = position_nudge(0.1), size=2) +
  geom_point(data = subset(tonicperc.esmmeans, condition == "SR"), aes(shape = condition), colour="#D55E00",fill="white", position = position_nudge(0.1), size=2) + 
  labs(x = "night", y = "% per total sleep time") + ggtitle("tonic") +
  scale_y_continuous(limits = c(12, 28), breaks = seq(12, 28, 2), expand = c(0, NA))+
  scale_x_discrete(labels=c("B", "1", "2", "3", "4", "5", "6", "7")) +
  theme_prism(base_size = 9, base_fontface="plain", base_line_size=0.2) 
tonicperc

WASOperc <- ggplot(wakeperc.esmmeans, aes(x = night, y = Mean, group=condition, shape=condition)) +
  scale_shape_manual(values = c(16,21)) + 
  geom_line(linewidth=0.3, position =   position_nudge(0.1)) +
  geom_errorbar(aes(x=night, y=Mean, ymin=Mean-SE, ymax=Mean+SE,), width=0.4, lwd=0.3, position = position_nudge(0.1)) +
  geom_point(data = subset(wakeperc.esmmeans, condition == "SE"), aes(shape = condition), position = position_nudge(0.1), size=2) +
  geom_point(data = subset(wakeperc.esmmeans, condition == "SR"), aes(shape = condition), fill="white", position = position_nudge(0.1), size=2) + 
  labs(x = "night", y = "% per total sleep time") + ggtitle("WASO") +
  scale_y_continuous(limits = c(-5, 20), breaks = seq(-5, 20, 5), expand = c(0, NA))+
 # scale_y_continuous(limits = c(15, 30), breaks = seq(15, 30, 5), expand = c(0, NA))+
  scale_x_discrete(labels=c("B", "1", "2", "3", "4", "5", "6", "7")) +
  theme_prism(base_size = 9, base_fontface="plain", base_line_size=0.2) 
WASOperc


NREMperc <- ggplot(NREMperc.esmmeans, aes(x = night, y = Mean, group=condition, shape=condition)) +
  scale_shape_manual(values = c(16,21)) + 
  geom_line(linewidth=0.3, position =   position_nudge(0.1)) +
  geom_errorbar(aes(x=night, y=Mean, ymin=Mean-SE, ymax=Mean+SE,), width=0.4, lwd=0.3, position = position_nudge(0.1)) +
  geom_point(data = subset(NREMperc.esmmeans, condition == "SE"), aes(shape = condition), position = position_nudge(0.1), size=2) +
  geom_point(data = subset(NREMperc.esmmeans, condition == "SR"), aes(shape = condition), fill="white", position = position_nudge(0.1), size=2) + 
  labs(x = "night", y = "% per total sleep time") + ggtitle("NREM (N2+N3)") +
  scale_y_continuous(limits = c(58, 74), breaks = seq(58, 74, 2), expand = c(0, NA))+
 # scale_y_continuous(limits = c(15, 30), breaks = seq(15, 30, 5), expand = c(0, NA))+
  scale_x_discrete(labels=c("B", "1", "2", "3", "4", "5", "6", "7")) +
  theme_prism(base_size = 9, base_fontface="plain", base_line_size=0.2) 
NREMperc


N1perc <- ggplot(N1perc.esmmeans, aes(x = night, y = Mean, group=condition, shape=condition)) +
  scale_shape_manual(values = c(16,21)) + 
  geom_line(linewidth=0.3, position =   position_nudge(0.1)) +
  geom_errorbar(aes(x=night, y=Mean, ymin=Mean-SE, ymax=Mean+SE,), width=0.4, lwd=0.3, position = position_nudge(0.1)) +
  geom_point(data = subset(N1perc.esmmeans, condition == "SE"), aes(shape = condition), position = position_nudge(0.1), size=2) +
  geom_point(data = subset(N1perc.esmmeans, condition == "SR"), aes(shape = condition), fill="white", position = position_nudge(0.1), size=2) + 
  labs(x = "night", y = "% per total sleep time") + ggtitle("N1") +
  scale_y_continuous(limits = c(6, 14), breaks = seq(6, 14, 1), expand = c(0, NA))+
 # scale_y_continuous(limits = c(15, 30), breaks = seq(15, 30, 5), expand = c(0, NA))+
  scale_x_discrete(labels=c("B", "1", "2", "3", "4", "5", "6", "7")) +
  theme_prism(base_size = 9, base_fontface="plain", base_line_size=0.2) 
N1perc


N2perc <- ggplot(N2perc.esmmeans, aes(x = night, y = Mean, group=condition, shape=condition)) +
  scale_shape_manual(values = c(16,21)) + 
  geom_line(linewidth=0.3, position =   position_nudge(0.1)) +
  geom_errorbar(aes(x=night, y=Mean, ymin=Mean-SE, ymax=Mean+SE,), width=0.4, lwd=0.3, position = position_nudge(0.1)) +
  geom_point(data = subset(N2perc.esmmeans, condition == "SE"), aes(shape = condition), position = position_nudge(0.1), size=2) +
  geom_point(data = subset(N2perc.esmmeans, condition == "SR"), aes(shape = condition), fill="white", position = position_nudge(0.1), size=2) + 
  labs(x = "night", y = "% per total sleep time") + ggtitle("N2") +
  scale_y_continuous(limits = c(25, 45), breaks = seq(25, 45, 5), expand = c(0, NA))+
 # scale_y_continuous(limits = c(15, 30), breaks = seq(15, 30, 5), expand = c(0, NA))+
  scale_x_discrete(labels=c("B", "1", "2", "3", "4", "5", "6", "7")) +
  theme_prism(base_size = 9, base_fontface="plain", base_line_size=0.2) 
N2perc


N3perc <- ggplot(N3perc.esmmeans, aes(x = night, y = Mean, group=condition, shape=condition)) +
  scale_shape_manual(values = c(16,21)) + 
  geom_line(linewidth=0.3, position =   position_nudge(0.1)) +
  geom_errorbar(aes(x=night, y=Mean, ymin=Mean-SE, ymax=Mean+SE,), width=0.4, lwd=0.3, position = position_nudge(0.1)) +
  geom_point(data = subset(N3perc.esmmeans, condition == "SE"), aes(shape = condition), position = position_nudge(0.1), size=2) +
  geom_point(data = subset(N3perc.esmmeans, condition == "SR"), aes(shape = condition), fill="white", position = position_nudge(0.1), size=2) + 
  labs(x = "night", y = "% per total sleep time") + ggtitle("N3") +
  scale_y_continuous(limits = c(15, 45), breaks = seq(15, 45, 5), expand = c(0, NA))+
 # scale_y_continuous(limits = c(15, 30), breaks = seq(15, 30, 5), expand = c(0, NA))+
  scale_x_discrete(labels=c("B", "1", "2", "3", "4", "5", "6", "7")) +
  theme_prism(base_size = 9, base_fontface="plain", base_line_size=0.2) 
N3perc



# percentage per common sleep duration
common_REMperc <- ggplot(common_REMperc.esmmeans, aes(x = night, y = Mean, group=condition, shape=condition)) +
  scale_shape_manual(values = c(16,21)) + 
  geom_line(linewidth=0.3, position =   position_nudge(0.1)) +
  geom_errorbar(aes(x=night, y=Mean, ymin=Mean-SE, ymax=Mean+SE,), width=0.4, lwd=0.3, position = position_nudge(0.1)) +
  geom_point(data = subset(common_REMperc.esmmeans, condition == "SE"), aes(shape = condition), position = position_nudge(0.1), size=2) +
  geom_point(data = subset(common_REMperc.esmmeans, condition == "SR"), aes(shape = condition), fill="white", position = position_nudge(0.1), size=2) + 
  labs(x = "night", y = "% per common sleep duration") + ggtitle("REM") +
  scale_y_continuous(limits = c(15, 30), breaks = seq(15, 30, 5), expand = c(0, NA))+
 # scale_y_continuous(limits = c(15, 30), breaks = seq(15, 30, 5), expand = c(0, NA))+
  scale_x_discrete(labels=c("B", "1", "2", "3", "4", "5", "6", "7")) +
  theme_prism(base_size = 9, base_fontface="plain", base_line_size=0.2) 
common_REMperc

common_phasicperc <- ggplot(common_phasicperc.esmmeans, aes(x = night, y = Mean, group=condition, shape=condition)) +
  scale_shape_manual(values = c(16,21)) + 
  geom_line(linewidth=0.3, position =   position_nudge(0.1), colour="#0072B2") +
  geom_errorbar(aes(x=night, y=Mean, ymin=Mean-SE, ymax=Mean+SE,), colour="#0072B2", width=0.4, lwd=0.3, position = position_nudge(0.1)) +
  geom_point(data = subset(common_phasicperc.esmmeans, condition == "SE"), aes(shape = condition), colour="#0072B2", position = position_nudge(0.1), size=2) +
  geom_point(data = subset(common_phasicperc.esmmeans, condition == "SR"), aes(shape = condition), colour="#0072B2", fill="white", position = position_nudge(0.1), size=2) + 
  labs(x = "night", y = "% per common sleep duration") + ggtitle("phasic") +
  scale_y_continuous(limits = c(0, 4), breaks = seq(0, 4, 0.5), expand = c(0, NA))+
 # scale_y_continuous(limits = c(15, 30), breaks = seq(15, 30, 5), expand = c(0, NA))+
  scale_x_discrete(labels=c("B", "1", "2", "3", "4", "5", "6", "7")) +
  theme_prism(base_size = 9, base_fontface="plain", base_line_size=0.2) 
common_phasicperc
 
common_tonicperc <- ggplot(common_tonicperc.esmmeans, aes(x = night, y = Mean, group=condition, shape=condition)) +
  scale_shape_manual(values = c(16,21)) + 
  geom_line(linewidth=0.3, position =   position_nudge(0.1), colour="#D55E00") +
  geom_errorbar(aes(x=night, y=Mean, ymin=Mean-SE, ymax=Mean+SE,), colour="#D55E00", width=0.4, lwd=0.3, position = position_nudge(0.1)) +
  geom_point(data = subset(common_tonicperc.esmmeans, condition == "SE"), aes(shape = condition), colour="#D55E00", position = position_nudge(0.1), size=2) +
  geom_point(data = subset(common_tonicperc.esmmeans, condition == "SR"), aes(shape = condition), colour="#D55E00",fill="white", position = position_nudge(0.1), size=2) + 
  labs(x = "night", y = "% per common sleep duration") + ggtitle("tonic") +
  scale_y_continuous(limits = c(12, 28), breaks = seq(12, 28, 2), expand = c(0, NA))+
  scale_x_discrete(labels=c("B", "1", "2", "3", "4", "5", "6", "7")) +
  theme_prism(base_size = 9, base_fontface="plain", base_line_size=0.2) 
common_tonicperc

common_WASOperc <- ggplot(common_wakeperc.esmmeans, aes(x = night, y = Mean, group=condition, shape=condition)) +
  scale_shape_manual(values = c(16,21)) + 
  geom_line(linewidth=0.3, position =   position_nudge(0.1)) +
  geom_errorbar(aes(x=night, y=Mean, ymin=Mean-SE, ymax=Mean+SE,), width=0.4, lwd=0.3, position = position_nudge(0.1)) +
  geom_point(data = subset(common_wakeperc.esmmeans, condition == "SE"), aes(shape = condition), position = position_nudge(0.1), size=2) +
  geom_point(data = subset(common_wakeperc.esmmeans, condition == "SR"), aes(shape = condition), fill="white", position = position_nudge(0.1), size=2) + 
  labs(x = "night", y = "% per common sleep duration") + ggtitle("WASO") +
  scale_y_continuous(limits = c(-5, 20), breaks = seq(-5, 20, 5), expand = c(0, NA))+
 # scale_y_continuous(limits = c(15, 30), breaks = seq(15, 30, 5), expand = c(0, NA))+
  scale_x_discrete(labels=c("B", "1", "2", "3", "4", "5", "6", "7")) +
  theme_prism(base_size = 9, base_fontface="plain", base_line_size=0.2) 
common_WASOperc


common_NREMperc <- ggplot(common_NREMperc.esmmeans, aes(x = night, y = Mean, group=condition, shape=condition)) +
  scale_shape_manual(values = c(16,21)) + 
  geom_line(linewidth=0.3, position =   position_nudge(0.1)) +
  geom_errorbar(aes(x=night, y=Mean, ymin=Mean-SE, ymax=Mean+SE,), width=0.4, lwd=0.3, position = position_nudge(0.1)) +
  geom_point(data = subset(common_NREMperc.esmmeans, condition == "SE"), aes(shape = condition), position = position_nudge(0.1), size=2) +
  geom_point(data = subset(common_NREMperc.esmmeans, condition == "SR"), aes(shape = condition), fill="white", position = position_nudge(0.1), size=2) + 
  labs(x = "night", y = "% per common sleep duration") + ggtitle("NREM (N2+N3)") +
  scale_y_continuous(limits = c(58, 74), breaks = seq(58, 74, 2), expand = c(0, NA))+
 # scale_y_continuous(limits = c(15, 30), breaks = seq(15, 30, 5), expand = c(0, NA))+
  scale_x_discrete(labels=c("B", "1", "2", "3", "4", "5", "6", "7")) +
  theme_prism(base_size = 9, base_fontface="plain", base_line_size=0.2) 
common_NREMperc


common_N1perc <- ggplot(common_N1perc.esmmeans, aes(x = night, y = Mean, group=condition, shape=condition)) +
  scale_shape_manual(values = c(16,21)) + 
  geom_line(linewidth=0.3, position =   position_nudge(0.1)) +
  geom_errorbar(aes(x=night, y=Mean, ymin=Mean-SE, ymax=Mean+SE,), width=0.4, lwd=0.3, position = position_nudge(0.1)) +
  geom_point(data = subset(common_N1perc.esmmeans, condition == "SE"), aes(shape = condition), position = position_nudge(0.1), size=2) +
  geom_point(data = subset(common_N1perc.esmmeans, condition == "SR"), aes(shape = condition), fill="white", position = position_nudge(0.1), size=2) + 
  labs(x = "night", y = "% per common sleep duration") + ggtitle("N1") +
  scale_y_continuous(limits = c(6, 14), breaks = seq(6, 14, 1), expand = c(0, NA))+
 # scale_y_continuous(limits = c(15, 30), breaks = seq(15, 30, 5), expand = c(0, NA))+
  scale_x_discrete(labels=c("B", "1", "2", "3", "4", "5", "6", "7")) +
  theme_prism(base_size = 9, base_fontface="plain", base_line_size=0.2) 
common_N1perc


common_N2perc <- ggplot(common_N2perc.esmmeans, aes(x = night, y = Mean, group=condition, shape=condition)) +
  scale_shape_manual(values = c(16,21)) + 
  geom_line(linewidth=0.3, position =   position_nudge(0.1)) +
  geom_errorbar(aes(x=night, y=Mean, ymin=Mean-SE, ymax=Mean+SE,), width=0.4, lwd=0.3, position = position_nudge(0.1)) +
  geom_point(data = subset(common_N2perc.esmmeans, condition == "SE"), aes(shape = condition), position = position_nudge(0.1), size=2) +
  geom_point(data = subset(common_N2perc.esmmeans, condition == "SR"), aes(shape = condition), fill="white", position = position_nudge(0.1), size=2) + 
  labs(x = "night", y = "% per common sleep duration") + ggtitle("N2") +
  scale_y_continuous(limits = c(25, 45), breaks = seq(25, 45, 5), expand = c(0, NA))+
 # scale_y_continuous(limits = c(15, 30), breaks = seq(15, 30, 5), expand = c(0, NA))+
  scale_x_discrete(labels=c("B", "1", "2", "3", "4", "5", "6", "7")) +
  theme_prism(base_size = 9, base_fontface="plain", base_line_size=0.2) 
common_N2perc


common_N3perc <- ggplot(common_N3perc.esmmeans, aes(x = night, y = Mean, group=condition, shape=condition)) +
  scale_shape_manual(values = c(16,21)) + 
  geom_line(linewidth=0.3, position =   position_nudge(0.1)) +
  geom_errorbar(aes(x=night, y=Mean, ymin=Mean-SE, ymax=Mean+SE,), width=0.4, lwd=0.3, position = position_nudge(0.1)) +
  geom_point(data = subset(common_N3perc.esmmeans, condition == "SE"), aes(shape = condition), position = position_nudge(0.1), size=2) +
  geom_point(data = subset(common_N3perc.esmmeans, condition == "SR"), aes(shape = condition), fill="white", position = position_nudge(0.1), size=2) + 
  labs(x = "night", y = "% per common sleep duration") + ggtitle("N3") +
  scale_y_continuous(limits = c(15, 45), breaks = seq(15, 45, 5), expand = c(0, NA))+
 # scale_y_continuous(limits = c(15, 30), breaks = seq(15, 30, 5), expand = c(0, NA))+
  scale_x_discrete(labels=c("B", "1", "2", "3", "4", "5", "6", "7")) +
  theme_prism(base_size = 9, base_fontface="plain", base_line_size=0.2) 
common_N3perc


# percentage per REM

phasicperREMperc <- ggplot(phasicperREMperc.esmmeans, aes(x = night, y = Mean, group=condition, shape=condition)) +
  scale_shape_manual(values = c(16,21)) + 
  geom_line(linewidth=0.3, position =   position_nudge(0.1), colour="#0072B2") +
  geom_errorbar(aes(x=night, y=Mean, ymin=Mean-SE, ymax=Mean+SE,), colour="#0072B2", width=0.4, lwd=0.3, position = position_nudge(0.1)) +
  geom_point(data = subset(phasicperREMperc.esmmeans, condition == "SE"), aes(shape = condition), colour="#0072B2", position = position_nudge(0.1), size=2) +
  geom_point(data = subset(phasicperREMperc.esmmeans, condition == "SR"), aes(shape = condition), colour="#0072B2", fill="white", position = position_nudge(0.1), size=2) + 
  labs(x = "night", y = "% per total REM") + ggtitle("phasic") +
  scale_y_continuous(limits = c(0, 15), breaks = seq(0, 15, 3), expand = c(0, NA))+
 # scale_y_continuous(limits = c(15, 30), breaks = seq(15, 30, 5), expand = c(0, NA))+
  scale_x_discrete(labels=c("B", "1", "2", "3", "4", "5", "6", "7")) +
  theme_prism(base_size = 9, base_fontface="plain", base_line_size=0.2) 
phasicperREMperc


tonicperREMperc <- ggplot(tonicperREMperc.esmmeans, aes(x = night, y = Mean, group=condition, shape=condition)) +
  scale_shape_manual(values = c(16,21)) + 
  geom_line(linewidth=0.3, position =   position_nudge(0.1), colour="#0072B2") +
  geom_errorbar(aes(x=night, y=Mean, ymin=Mean-SE, ymax=Mean+SE,), colour="#0072B2", width=0.4, lwd=0.3, position = position_nudge(0.1)) +
  geom_point(data = subset(tonicperREMperc.esmmeans, condition == "SE"), aes(shape = condition), colour="#0072B2", position = position_nudge(0.1), size=2) +
  geom_point(data = subset(tonicperREMperc.esmmeans, condition == "SR"), aes(shape = condition), colour="#0072B2", fill="white", position = position_nudge(0.1), size=2) + 
  labs(x = "night", y = "% per total REM") + ggtitle("tonic") +
  scale_y_continuous(limits = c(80, 100), breaks = seq(80, 100, 5), expand = c(0, NA))+
 # scale_y_continuous(limits = c(15, 30), breaks = seq(15, 30, 5), expand = c(0, NA))+
  scale_x_discrete(labels=c("B", "1", "2", "3", "4", "5", "6", "7")) +
  theme_prism(base_size = 9, base_fontface="plain", base_line_size=0.2) 
tonicperREMperc

```
#6 Table for absolute values (Table S1)
```{r}
df_average <- df_week %>% 
  dplyr::select(c(1:12)) %>% 
  group_by(night, condition) %>% 
  dplyr::summarise(across(where(is.numeric),
                   list(mean = ~mean(.x, na.rm = TRUE),
                        sem = ~sd(.x, na.rm = TRUE) / sqrt(sum(!is.na(.x)))),
                   .names = "{.col}_{.fn}"))

```

