---
title: "to produce table from raw data for statistical analysis - oscillatory components"
output: html_notebook
---

## Import functions 
```{r}
library(lmerTest)
library(emmeans)
library(lme4)
library(tidyverse)
library(broom)
library(devtools)
library(sjPlot)
library(modelbased)
library(nplyr)
library(dplyr)
```
## --- to produce df_oscillation (baseline stats) ---
## Load raw data
```{r}
df <- read_csv("osc_table_allsub_not_individualized_2_6_12_1s_osc_21-Jul-2026.csv", show_col_types = FALSE)
tst_allsub <- read_csv("tst_allsub.csv", show_col_types = FALSE)

# put in order of treatment: SE-> SR =1, SR-> SE = 2
df <- df %>%  
mutate(order = ifelse(participant=="AFOSR_AF0182"|participant=="AFOSR_AF0233"|participant=="AFOSR_AF0205"|participant=="AFOSR_AF0256"|participant=="AFOSR_AF0280"|participant=="AFOSR_AF0286"|participant=="AFOSR_AF0314"|participant=="AFOSR_AF0320"|participant=="AFOSR_AF0355"|participant=="AFOSR_AF0361"|participant=="AFOSR_AF0378"|participant=="AFOSR_AF0386"|participant=="AFOSR_AF0388"|participant=="AFOSR_AF0399"|participant=="AFOSR_AF0465"|participant=="AFOSR_AF0467"|participant=="AFOSR_AF0468"|participant=="AFOSR_AF0469"|participant=="AFOSR_AF0490"|participant=="AFOSR_AF0496",1,2)) %>% 
mutate_all(~ifelse(is.na(.), NaN, .))

# put in tst 
df <- df %>%  
  group_by(participant, channel, state) %>% 
  nest() 

# create empty df for loops
df_AF0165_all <- data.frame()
df_AF0170_all <- data.frame()
df_AF0182_all <- data.frame()
df_AF0205_all <- data.frame()
df_AF0214_all <- data.frame()
df_AF0233_all <- data.frame()
df_AF0250_all <- data.frame()
df_AF0256_all <- data.frame()
df_AF0280_all <- data.frame()
df_AF0286_all <- data.frame()
df_AF0288_all <- data.frame()
df_AF0295_all <- data.frame()
df_AF0307_all <- data.frame()
df_AF0309_all <- data.frame()
df_AF0314_all <- data.frame()
df_AF0318_all <- data.frame()
df_AF0320_all <- data.frame()
df_AF0336_all <- data.frame()
df_AF0355_all <- data.frame()
df_AF0361_all <- data.frame()
df_AF0378_all <- data.frame()
df_AF0386_all <- data.frame()
df_AF0388_all <- data.frame()
df_AF0399_all <- data.frame()
df_AF0406_all <- data.frame()
df_AF0409_all <- data.frame()
df_AF0411_all <- data.frame()
df_AF0421_all <- data.frame()
df_AF0431_all <- data.frame()
df_AF0438_all <- data.frame()
df_AF0465_all <- data.frame()
df_AF0467_all <- data.frame()
df_AF0468_all <- data.frame()
df_AF0469_all <- data.frame()
df_AF0490_all <- data.frame()
df_AF0496_all <- data.frame()

# loop to add tst (taken from tst_allsub table and create df which adds at every loop, somehow it doesnt just add into old df which was what I wanted!)
for (i in 1:nrow(df)) {
  if(df[[1]][[i]] =="AFOSR_AF0165"){
    sub1=tst_allsub[,1, drop=FALSE] # drop=False allows u to collect one column as it is instead of making it into list automatically
    df_AF0165 <- cbind(df$data[[i]], sub1)
    df_AF0165_all <- rbind(df_AF0165_all, df_AF0165)
  } else if(df[[1]][[i]] =="AFOSR_AF0170"){
      sub2=tst_allsub[,2, drop=FALSE]
      df_AF0170 <- cbind(df$data[[i]], sub2)
      df_AF0170_all <- rbind(df_AF0170_all, df_AF0170)
  } else if(df[[1]][[i]] =="AFOSR_AF0182"){
     sub3=tst_allsub[,3, drop=FALSE]
    df_AF0182 <- cbind(df$data[[i]], sub3)
    df_AF0182_all <- rbind(df_AF0182_all, df_AF0182)
  } else if(df[[1]][[i]] =="AFOSR_AF0205"){
     sub4=tst_allsub[,4, drop=FALSE]
    df_AF0205 <- cbind(df$data[[i]], sub4)
    df_AF0205_all <- rbind(df_AF0205_all, df_AF0205)
  } else if(df[[1]][[i]] =="AFOSR_AF0214"){
         sub5=tst_allsub[,5, drop=FALSE]
    df_AF0214 <- cbind(df$data[[i]], sub5)
    df_AF0214_all <- rbind(df_AF0214_all, df_AF0214)
  } else if(df[[1]][[i]] =="AFOSR_AF0233"){
         sub6=tst_allsub[,6, drop=FALSE]
    df_AF0233 <- cbind(df$data[[i]], sub6)
    df_AF0233_all <- rbind(df_AF0233_all, df_AF0205)
  } else if(df[[1]][[i]] =="AFOSR_AF0250"){
         sub7=tst_allsub[,7, drop=FALSE]
    df_AF0250 <- cbind(df$data[[i]], sub7)
    df_AF0250_all <- rbind(df_AF0250_all, df_AF0205)
  } else if(df[[1]][[i]] =="AFOSR_AF0256"){
        sub8=tst_allsub[,8, drop=FALSE]
    df_AF0256 <- cbind(df$data[[i]], sub8)
    df_AF0256_all <- rbind(df_AF0256_all, df_AF0256)
  } else if(df[[1]][[i]] =="AFOSR_AF0280"){
         sub9=tst_allsub[,9, drop=FALSE]
    df_AF0280 <- cbind(df$data[[i]], sub9)
    df_AF0280_all <- rbind(df_AF0280_all, df_AF0280)
  } else if(df[[1]][[i]] =="AFOSR_AF0286"){
        sub10=tst_allsub[,10, drop=FALSE]
    df_AF0286 <- cbind(df$data[[i]], sub10)
    df_AF0286_all <- rbind(df_AF0286_all, df_AF0286)
  } else if(df[[1]][[i]] =="AFOSR_AF0288"){
         sub11=tst_allsub[,11, drop=FALSE]
    df_AF0288 <- cbind(df$data[[i]], sub11)
    df_AF0288_all <- rbind(df_AF0288_all, df_AF0288)
  } else if(df[[1]][[i]] =="AFOSR_AF0295"){
        sub12=tst_allsub[,12, drop=FALSE]
    df_AF0295 <- cbind(df$data[[i]], sub12)
    df_AF0295_all <- rbind(df_AF0295_all, df_AF0295)
  } else if(df[[1]][[i]] =="AFOSR_AF0307"){
        sub13=tst_allsub[,13, drop=FALSE]
    df_AF0307 <- cbind(df$data[[i]], sub13)
    df_AF0307_all <- rbind(df_AF0307_all, df_AF0307)
  } else if(df[[1]][[i]] =="AFOSR_AF0309"){
         sub14=tst_allsub[,14, drop=FALSE]
    df_AF0309 <- cbind(df$data[[i]], sub14)
    df_AF0309_all <- rbind(df_AF0309_all, df_AF0309)
  } else if(df[[1]][[i]] =="AFOSR_AF0314"){
        sub15=tst_allsub[,15, drop=FALSE]
    df_AF0314 <- cbind(df$data[[i]], sub15)
    df_AF0314_all <- rbind(df_AF0314_all, df_AF0314)
  } else if(df[[1]][[i]] =="AFOSR_AF0318"){
         sub16=tst_allsub[,16, drop=FALSE]
    df_AF0318 <- cbind(df$data[[i]], sub16)
    df_AF0318_all <- rbind(df_AF0318_all, df_AF0318)
  } else if(df[[1]][[i]] =="AFOSR_AF0320"){
         sub17=tst_allsub[,17, drop=FALSE]
    df_AF0320 <- cbind(df$data[[i]], sub17)
    df_AF0320_all <- rbind(df_AF0320_all, df_AF0320)

  } else if(df[[1]][[i]] =="AFOSR_AF0336"){
         sub18=tst_allsub[,18, drop=FALSE]
    df_AF0336 <- cbind(df$data[[i]], sub18)
    df_AF0336_all <- rbind(df_AF0336_all, df_AF0336)
  } else if(df[[1]][[i]] =="AFOSR_AF0355"){
         sub19=tst_allsub[,19, drop=FALSE]
    df_AF0355 <- cbind(df$data[[i]], sub19)
    df_AF0355_all <- rbind(df_AF0355_all, df_AF0355)
  } else if(df[[1]][[i]] =="AFOSR_AF0361"){
        sub20=tst_allsub[,20, drop=FALSE]
    df_AF0361 <- cbind(df$data[[i]], sub20)
    df_AF0361_all <- rbind(df_AF0361_all, df_AF0361)
  } else if(df[[1]][[i]] =="AFOSR_AF0378"){
         sub21=tst_allsub[,21, drop=FALSE]
    df_AF0378 <- cbind(df$data[[i]], sub21)
    df_AF0378_all <- rbind(df_AF0378_all, df_AF0378)
  } else if(df[[1]][[i]] =="AFOSR_AF0386"){
         sub22=tst_allsub[,22, drop=FALSE]
    df_AF0386 <- cbind(df$data[[i]], sub22)
    df_AF0386_all <- rbind(df_AF0386_all, df_AF0386)
  } else if(df[[1]][[i]] =="AFOSR_AF0388"){
         sub23=tst_allsub[,23, drop=FALSE]
    df_AF0388 <- cbind(df$data[[i]], sub23)
    df_AF0388_all <- rbind(df_AF0388_all, df_AF0388)
  } else if(df[[1]][[i]] =="AFOSR_AF0399"){
         sub24=tst_allsub[,24, drop=FALSE]
    df_AF0399 <- cbind(df$data[[i]], sub24)
    df_AF0399_all <- rbind(df_AF0399_all, df_AF0399)
  } else if(df[[1]][[i]] =="AFOSR_AF0406"){
         sub25=tst_allsub[,25, drop=FALSE]
    df_AF0406 <- cbind(df$data[[i]], sub25)
    df_AF0406_all <- rbind(df_AF0406_all, df_AF0406)
  } else if(df[[1]][[i]] =="AFOSR_AF0409"){
         sub26=tst_allsub[,26, drop=FALSE]
    df_AF0409 <- cbind(df$data[[i]], sub26)
    df_AF0409_all <- rbind(df_AF0409_all, df_AF0409)
  } else if(df[[1]][[i]] =="AFOSR_AF0411"){
         sub27=tst_allsub[,27, drop=FALSE]
    df_AF0411 <- cbind(df$data[[i]], sub27)
    df_AF0411_all <- rbind(df_AF0411_all, df_AF0411)
  } else if(df[[1]][[i]] =="AFOSR_AF0421"){
         sub28=tst_allsub[,28, drop=FALSE]
    df_AF0421 <- cbind(df$data[[i]], sub28)
    df_AF0421_all <- rbind(df_AF0421_all, df_AF0421)
  } else if(df[[1]][[i]] =="AFOSR_AF0431"){
         sub29=tst_allsub[,29, drop=FALSE]
    df_AF0431 <- cbind(df$data[[i]], sub29)
    df_AF0431_all <- rbind(df_AF0431_all, df_AF0431)
  } else if(df[[1]][[i]] =="AFOSR_AF0438"){
         sub30=tst_allsub[,30, drop=FALSE]
    df_AF0438 <- cbind(df$data[[i]], sub30)
    df_AF0438_all <- rbind(df_AF0438_all, df_AF0438)
  } else if(df[[1]][[i]] =="AFOSR_AF0465"){
         sub31=tst_allsub[,31, drop=FALSE]
    df_AF0465 <- cbind(df$data[[i]], sub31)
    df_AF0465_all <- rbind(df_AF0465_all, df_AF0465)
  } else if(df[[1]][[i]] =="AFOSR_AF0467"){
         sub32=tst_allsub[,32, drop=FALSE]
    df_AF0467 <- cbind(df$data[[i]], sub32)
    df_AF0467_all <- rbind(df_AF0467_all, df_AF0467)
  } else if(df[[1]][[i]] =="AFOSR_AF0468"){
         sub33=tst_allsub[,33, drop=FALSE]
    df_AF0468 <- cbind(df$data[[i]], sub33)
    df_AF0468_all <- rbind(df_AF0468_all, df_AF0468)
  } else if(df[[1]][[i]] =="AFOSR_AF0469"){
        sub34=tst_allsub[,34, drop=FALSE]
    df_AF0469 <- cbind(df$data[[i]], sub34)
    df_AF0469_all <- rbind(df_AF0469_all, df_AF0469)
  } else if(df[[1]][[i]] =="AFOSR_AF0490"){
          sub35=tst_allsub[,35, drop=FALSE]
    df_AF0490 <- cbind(df$data[[i]], sub35)
    df_AF0490_all <- rbind(df_AF0490_all, df_AF0490)
  } else if(df[[1]][[i]] =="AFOSR_AF0496"){   
     sub36=tst_allsub[,36, drop=FALSE]
    df_AF0496 <- cbind(df$data[[i]], sub36)
    df_AF0496_all <- rbind(df_AF0496_all, df_AF0496)
  }
}

# change column names
colnames(df_AF0165_all)[22] <- 'tst'
colnames(df_AF0170_all)[22] <- 'tst'
colnames(df_AF0182_all)[22] <- 'tst'
colnames(df_AF0205_all)[22] <- 'tst'
colnames(df_AF0214_all)[22] <- 'tst'
colnames(df_AF0233_all)[22] <- 'tst'
colnames(df_AF0250_all)[22] <- 'tst'
colnames(df_AF0256_all)[22] <- 'tst'
colnames(df_AF0280_all)[22] <- 'tst'
colnames(df_AF0286_all)[22] <- 'tst'
colnames(df_AF0288_all)[22] <- 'tst'
colnames(df_AF0295_all)[22] <- 'tst'
colnames(df_AF0307_all)[22] <- 'tst'
colnames(df_AF0309_all)[22] <- 'tst'
colnames(df_AF0314_all)[22] <- 'tst'
colnames(df_AF0318_all)[22] <- 'tst'
colnames(df_AF0320_all)[22] <- 'tst'
colnames(df_AF0336_all)[22] <- 'tst'
colnames(df_AF0355_all)[22] <- 'tst'
colnames(df_AF0361_all)[22] <- 'tst'
colnames(df_AF0378_all)[22] <- 'tst'
colnames(df_AF0386_all)[22] <- 'tst'
colnames(df_AF0388_all)[22] <- 'tst'
colnames(df_AF0399_all)[22] <- 'tst'
colnames(df_AF0406_all)[22] <- 'tst'
colnames(df_AF0409_all)[22] <- 'tst'
colnames(df_AF0411_all)[22] <- 'tst'
colnames(df_AF0421_all)[22] <- 'tst'
colnames(df_AF0431_all)[22] <- 'tst'
colnames(df_AF0438_all)[22] <- 'tst'
colnames(df_AF0465_all)[22] <- 'tst'
colnames(df_AF0467_all)[22] <- 'tst'
colnames(df_AF0468_all)[22] <- 'tst'
colnames(df_AF0469_all)[22] <- 'tst'
colnames(df_AF0490_all)[22] <- 'tst'
colnames(df_AF0496_all)[22] <- 'tst'

df <- df %>% 
  unnest()
partcipant_list <- as.data.frame(df[[1]])
rest_of_df <- bind_rows(df_AF0165_all, df_AF0170_all, df_AF0182_all, df_AF0205_all, df_AF0214_all, df_AF0233_all,
                    df_AF0250_all, df_AF0256_all, df_AF0280_all, df_AF0286_all, df_AF0288_all, df_AF0295_all,
                    df_AF0307_all, df_AF0309_all, df_AF0314_all, df_AF0318_all, df_AF0320_all, df_AF0336_all,
                    df_AF0355_all, df_AF0361_all, df_AF0378_all, df_AF0386_all, df_AF0388_all, df_AF0399_all, 
                    df_AF0406_all, df_AF0409_all, df_AF0411_all, df_AF0421_all, df_AF0431_all, df_AF0438_all,
                    df_AF0465_all, df_AF0467_all, df_AF0468_all, df_AF0469_all, df_AF0490_all, df_AF0496_all)

tst <- rest_of_df$tst
df <- add_column(df, tst, .after = 5)
rm(list = setdiff(ls(), "df"))  # Remove all but df
```
# Average channels 
```{r}
df_wide <- df %>% 
  pivot_wider(names_from = channel, values_from = c(7:24))

df_average <- df_wide %>% 
  mutate(frontal_IAPF = (IAPF_F3 + IAPF_F4)/2) %>%
  mutate(central_IAPF = (IAPF_C3 + IAPF_C4)/2) %>%
  mutate(parietal_IAPF = (IAPF_P3 + IAPF_P4)/2) %>%
  mutate(occipital_IAPF = (IAPF_O1 + IAPF_O2)/2) %>%
  mutate(frontal_ITPF = (ITPF_F3 + ITPF_F4)/2) %>%
  mutate(central_ITPF = (ITPF_C3 + ITPF_C4)/2) %>%
  mutate(parietal_ITPF = (ITPF_P3 + ITPF_P4)/2) %>%
  mutate(occipital_ITPF = (ITPF_O1 + ITPF_O2)/2) %>%
  mutate(frontal_ISPF = (ISPF_F3 + ISPF_F4)/2) %>%
  mutate(central_ISPF = (ISPF_C3 + ISPF_C4)/2) %>%
  mutate(parietal_ISPF = (ISPF_P3 + ISPF_P4)/2) %>%
  mutate(occipital_ISPF = (ISPF_O1 + ISPF_O2)/2) %>% 
  mutate(frontal_heightIAPF = (height_IAPF_F3 + height_IAPF_F4)/2) %>%
  mutate(central_heightIAPF = (height_IAPF_C3 + height_IAPF_C4)/2) %>%
  mutate(parietal_heightIAPF = (height_IAPF_P3 + height_IAPF_P4)/2) %>%
  mutate(occipital_heightIAPF = (height_IAPF_O1 + height_IAPF_O2)/2) %>%
  mutate(frontal_heightITPF = (height_ITPF_F3 + height_ITPF_F4)/2) %>%
  mutate(central_heightITPF = (height_ITPF_C3 + height_ITPF_C4)/2) %>%
  mutate(parietal_heightITPF = (height_ITPF_P3 + height_ITPF_P4)/2) %>%
  mutate(occipital_heightITPF = (height_ITPF_O1 + height_ITPF_O2)/2) %>%
  mutate(frontal_heightISPF = (height_ISPF_F3 + height_ISPF_F4)/2) %>%
  mutate(central_heightISPF = (height_ISPF_C3 + height_ISPF_C4)/2) %>%
  mutate(parietal_heightISPF = (height_ISPF_P3 + height_ISPF_P4)/2) %>%
  mutate(occipital_heightISPF = (height_ISPF_O1 + height_ISPF_O2)/2) %>% 
  mutate(frontal_densityalpha = (density_alpha_F3 + density_alpha_F4)/2) %>%
  mutate(central_densityalpha = (density_alpha_C3 + density_alpha_C4)/2) %>%
  mutate(parietal_densityalpha = (density_alpha_P3 + density_alpha_P4)/2) %>%
  mutate(occipital_densityalpha = (density_alpha_O1 + density_alpha_O2)/2) %>%
  mutate(frontal_densitytheta = (density_theta_F3 + density_theta_F4)/2) %>%
  mutate(central_densitytheta = (density_theta_C3 + density_theta_C4)/2) %>%
  mutate(parietal_densitytheta = (density_theta_P3 + density_theta_P4)/2) %>%
  mutate(occipital_densitytheta = (density_theta_O1 + density_theta_O2)/2) %>%
  mutate(frontal_densityspindles = (density_spindles_F3 + density_spindles_F4)/2) %>%
  mutate(central_densityspindles = (density_spindles_C3 + density_spindles_C4)/2) %>%
  mutate(parietal_densityspindles = (density_spindles_P3 + density_spindles_P4)/2) %>%
  mutate(occipital_densityspindles = (density_spindles_O1 + density_spindles_O2)/2) %>% 
  mutate(frontal_abundancealpha = (abundance_alpha_F3 + abundance_alpha_F4)/2) %>%
  mutate(central_abundancealpha = (abundance_alpha_C3 + abundance_alpha_C4)/2) %>%
  mutate(parietal_abundancealpha = (abundance_alpha_P3 + abundance_alpha_P4)/2) %>%
  mutate(occipital_abundancealpha = (abundance_alpha_O1 + abundance_alpha_O2)/2) %>%
  mutate(frontal_abundancetheta = (abundance_theta_F3 + abundance_theta_F4)/2) %>%
  mutate(central_abundancetheta = (abundance_theta_C3 + abundance_theta_C4)/2) %>%
  mutate(parietal_abundancetheta = (abundance_theta_P3 + abundance_theta_P4)/2) %>%
  mutate(occipital_abundancetheta = (abundance_theta_O1 + abundance_theta_O2)/2) %>%
  mutate(frontal_abundancespindles = (abundance_spindles_F3 + abundance_spindles_F4)/2) %>%
  mutate(central_abundancespindles = (abundance_spindles_C3 + abundance_spindles_C4)/2) %>%
  mutate(parietal_abundancespindles = (abundance_spindles_P3 + abundance_spindles_P4)/2) %>%
  mutate(occipital_abundancespindles = (abundance_spindles_O1 + abundance_spindles_O2)/2) %>% 
  mutate(frontal_amplitudealpha = (amplitude_alpha_F3 + amplitude_alpha_F4)/2) %>%
  mutate(central_amplitudealpha = (amplitude_alpha_C3 + amplitude_alpha_C4)/2) %>%
  mutate(parietal_amplitudealpha = (amplitude_alpha_P3 + amplitude_alpha_P4)/2) %>%
  mutate(occipital_amplitudealpha = (amplitude_alpha_O1 + amplitude_alpha_O2)/2) %>%
  mutate(frontal_amplitudetheta = (amplitude_theta_F3 + amplitude_theta_F4)/2) %>%
  mutate(central_amplitudetheta = (amplitude_theta_C3 + amplitude_theta_C4)/2) %>%
  mutate(parietal_amplitudetheta = (amplitude_theta_P3 + amplitude_theta_P4)/2) %>%
  mutate(occipital_amplitudetheta = (amplitude_theta_O1 + amplitude_theta_O2)/2) %>%
  mutate(frontal_amplitudespindles = (amplitude_spindles_F3 + amplitude_spindles_F4)/2) %>%
  mutate(central_amplitudespindles = (amplitude_spindles_C3 + amplitude_spindles_C4)/2) %>%
  mutate(parietal_amplitudespindles = (amplitude_spindles_P3 + amplitude_spindles_P4)/2) %>%
  mutate(occipital_amplitudespindles = (amplitude_spindles_O1 + amplitude_spindles_O2)/2) %>% 
  mutate(frontal_snralpha = (snr_alpha_F3 + snr_alpha_F4)/2) %>%
  mutate(central_snralpha = (snr_alpha_C3 + snr_alpha_C4)/2) %>%
  mutate(parietal_snralpha = (snr_alpha_P3 + snr_alpha_P4)/2) %>%
  mutate(occipital_snralpha = (snr_alpha_O1 + snr_alpha_O2)/2) %>%
  mutate(frontal_snrtheta = (snr_theta_F3 + snr_theta_F4)/2) %>%
  mutate(central_snrtheta = (snr_theta_C3 + snr_theta_C4)/2) %>%
  mutate(parietal_snrtheta = (snr_theta_P3 + snr_theta_P4)/2) %>%
  mutate(occipital_snrtheta = (snr_theta_O1 + snr_theta_O2)/2) %>%
  mutate(frontal_snrspindles = (snr_spindles_F3 + snr_spindles_F4)/2) %>%
  mutate(central_snrspindles = (snr_spindles_C3 + snr_spindles_C4)/2) %>%
  mutate(parietal_snrspindles = (snr_spindles_P3 + snr_spindles_P4)/2) %>%
  mutate(occipital_snrspindles = (snr_spindles_O1 + snr_spindles_O2)/2)

df_average <- df_average %>%
  dplyr:: select(!c(7:150)) 

df_average <- df_average %>% 
  pivot_longer(
    cols = c(7:78),
      names_to = c("channel", ".value"), # takes however many value that corresponds to channel
      names_sep="_" )


```
# Factorise
```{r}
cols <- c("participant", "condition", "night", "order", "state", "channel")
df_average <- df_average %>% mutate_at(cols, factor)
factor(df_average$night, order=TRUE,
       levels= c("1", "2", "3", "4", "5", "6", "7", "8", "9"))

df_average <- df_average %>%
 filter(!night == "9")

# for baseline stats
saveRDS(df_average, "C:/Users/swong3/OneDrive - Imperial College London/Documents/R/airforce_data/data/FOR PAPER/July 2026/oscillatory/stats/df_oscillations_27July26.rds")

```
## --- to produce df_oscillation_week (whole week stats) ---
# append baseline values for whole week stats
```{r}
rm(list = ls()[-match(c("df", "df_average"), ls())])

# Extract baseline values and append to original frame 
baselinevalues <-df_average %>% 
  filter(night == "1") %>% 
  group_by(state,condition) %>% 
  nest() %>% 
  nest_transmute(data,
    IAPF_baseline = IAPF,
    ITPF_baseline = ITPF,
    ISPF_baseline = ISPF,
    heightIAPF_baseline = heightIAPF,
    heightITPF_baseline = heightITPF,
    heightISPF_baseline = heightISPF,
    densityalpha_baseline = densityalpha,
    densitytheta_baseline = densitytheta,
    densityspindles_baseline = densityspindles,
    abundancealpha_baseline = abundancealpha,
    abundancetheta_baseline = abundancetheta,
    abundancespindles_baseline = abundancespindles,
    amplitudealpha_baseline =  amplitudealpha,
    amplitudetheta_baseline =  amplitudetheta,
    amplitudespindles_baseline = amplitudespindles,
    snralpha_baseline =  snralpha,
    snrtheta_baseline =  snrtheta,
    snrspindles_baseline = snrspindles) %>% 
   nest_slice(data, 
              rep(1:n(), times = 8))
  
df_average_full <- df_average %>% 
  group_by(state,condition) %>% 
  nest() %>% 
  nest_arrange(data, night)

# ---
df_average_full[[3]][[1]] <- cbind(df_average_full[[3]][[1]],baselinevalues[[3]][[1]])
df_average_full[[3]][[2]] <- cbind(df_average_full[[3]][[2]],baselinevalues[[3]][[2]])
df_average_full[[3]][[3]] <- cbind(df_average_full[[3]][[3]],baselinevalues[[3]][[3]])
df_average_full[[3]][[4]] <- cbind(df_average_full[[3]][[4]],baselinevalues[[3]][[4]])
df_average_full[[3]][[5]] <- cbind(df_average_full[[3]][[5]],baselinevalues[[3]][[5]])
df_average_full[[3]][[6]] <- cbind(df_average_full[[3]][[6]],baselinevalues[[3]][[6]])
df_average_full[[3]][[7]] <- cbind(df_average_full[[3]][[7]],baselinevalues[[3]][[7]])
df_average_full[[3]][[8]] <- cbind(df_average_full[[3]][[8]],baselinevalues[[3]][[8]])
df_average_full[[3]][[9]] <- cbind(df_average_full[[3]][[9]],baselinevalues[[3]][[9]])
df_average_full[[3]][[10]] <- 
cbind(df_average_full[[3]][[10]],baselinevalues[[3]][[10]])


#---
df_average_full <- unnest(df_average_full)

cols <- c("participant", "condition", "night", "order", "state")
df_average_full <- df_average_full %>% mutate_at(cols, factor)
factor(df_average_full$night, order=TRUE,
       levels= c("1", "2", "3", "4", "5", "6", "7", "8", "9"))

df_q2 <- df_average_full %>%
  filter(!night == "9") 

saveRDS(df_q2, "C:/Users/swong3/OneDrive - Imperial College London/Documents/R/airforce_data/data/FOR PAPER/July 2026/oscillatory/stats/df_oscillations_week_27July26.rds")
```