---
title: "slope stats"
output: html_notebook
---

# Import functions
```{r}
library(devtools)
library(lmerTest)
library(lme4)
library(emmeans)
library(tidyverse)
library(broom)
library(kableExtra)
library(ggpubr)
library(ggprism)
```

## Looking at baseline nights only, differences between wake/NREM/REM and phasic/tonic (Fig2, S2) 
```{r}
# load data
df_slope <- read_csv("data/for paper/slope (aperiodic)/df_slope.csv", show_col_types = FALSE)

# Factorise
cols <- c("participant", "condition", "night", "order", "state", "channel")
df_slope <- df_slope %>% mutate_at(cols, factor)
factor(df_slope$night, order=TRUE,
       levels= c("1", "2", "3", "4", "5", "6", "7", "8"))

```
# 1. lmes
```{r}
df_baseline <- df_slope %>%
  filter(night == "1") %>%
   filter(state=="phasic" | state == "tonic")
 # filter(state == "wake" | state == "NREM" | state == "REM")

fit.baseline_exp1to30 <- lmer(exp1to30 ~ state*channel + order + tst + (1|participant), data=df_baseline)
anova.baseline_exp1to30 <-  anova(fit.baseline_exp1to30)

fit.baseline_exp30to45 <- lmer(exp30to45 ~ state*channel + order + tst + (1|participant), data=df_baseline)
anova.baseline_exp30to45 <-  anova(fit.baseline_exp30to45)

# estimated means
baseline_exp1to30_statechannel_esmmeans <- estimate_means(fit.baseline_exp1to30, by = c("state","channel"))
baseline_exp30to45_statechannel_esmmeans <- estimate_means(fit.baseline_exp30to45, by = c("state","channel"))
```
#2. posthoc
```{r}
# compare channels for each state
pairs(emmeans(fit.baseline_exp1to30, ~state:channel, by="channel", p.adjust = "tukey"))
pairs(emmeans(fit.baseline_exp30to45, ~state:channel, by="channel", p.adjust = "tukey"))
```
#3 plot
```{r}
# average across channel and nights for visualisation
df_baseline_average <- df_baseline %>% 
  select(c(1,2,8,9,10,11)) %>% 
  group_by(participant, state) %>% 
  dplyr::summarise(across(everything(), mean, na.rm=TRUE))

exp30to45_base <- ggplot(df_baseline_average, aes(x = state, y = exp30to45, fill = state)) +
  # Left half violin for phasic
  geom_half_violin(data = subset(df_baseline_average, state == "phasic"),side = "l",  # <-- flip to left
 alpha = 0.8, trim = FALSE, position = position_nudge(x = -0.1)) +
# Right half violin for tonic
  geom_half_violin(data = subset(df_baseline_average, state == "tonic"),side = "r", alpha = 0.8, trim = FALSE, position = position_nudge(x = 0.1)) +
# join same participants with line across state
   geom_line(aes(group = participant), colour = "black", linewidth = 0.3, alpha = 0.2, position = position_jitter(width = 0.05, seed = 123)) +
  geom_point(aes(shape = state, colour=state), size=1, position = position_jitter(width = 0.05, seed = 123)) +
#colorBlindBlack8  <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
  scale_fill_manual(values = c("phasic" = "#0072B2", "tonic" = "#D55E00")) + 
  scale_colour_manual(values = c("phasic" = "#0072B2", "tonic" = "#D55E00")) + 
  scale_shape_manual(values = c(21,21)) +
  scale_y_continuous(limits = c(-6, -1.5), breaks = seq(-6, -1.5, 0.5), expand = c(0, NA)) + # set scales to begin at , intervals of 3 until highest value , expand prevents padding at top and bottom of y axis so it will be in line with x axis
  ylab(expression("spectral slope 30-45 Hz "~(mu*V^2/Hz))) +
  theme_prism(base_size = 11, base_fontface="plain", base_line_size=0.2) +
  theme(legend.position = "none")

  # add error bar and mean for phasic (esmmeans)
exp30to45_base <- exp30to45_base +
   geom_errorbar(data = subset(baseline_exp30to45_state_esmmeans, state == "phasic"), aes(x=state, y=Mean, ymin=Mean-SE, ymax=Mean+SE), width=0.1, lwd=0.5, position = position_nudge(x = -0.2)) +
    geom_point(data = subset(baseline_exp30to45_state_esmmeans, state == "phasic"), aes(x=state, y=Mean, shape=state, colour=state), fill="#0072B2", colour="black", size =2,  position = position_nudge(x = -0.2)) +
   # add error bar and mean for tonic (esmmeans)
    geom_errorbar(data = subset(baseline_exp30to45_state_esmmeans, state == "tonic"), aes(x=state, y=Mean, ymin=Mean-SE, ymax=Mean+SE), width=0.1, lwd=0.5, position = position_nudge(x = 0.2)) +
    geom_point(data = subset(baseline_exp30to45_state_esmmeans, state == "tonic"), aes(x=state, y=Mean, shape=state, colour=state),colour="black", size =2,  position = position_nudge(x = 0.2))  +
 # geom_line(data = baseline_ITPF_state_esmmeans, aes(x=state, y=Mean, group=1), colour = "black", linewidth = 1) +
  scale_x_discrete(name = NULL)  
```

## Looking at the whole week, changes in phasic and tonic (Fig3)
```{r}
# load data
df_slope_week <- read_csv("data/for paper/slope (aperiodic)/df_slope_week.csv", show_col_types = FALSE)

# Factorise
cols <- c("participant", "condition", "night", "order", "state", "channel")
df_slope <- df_slope %>% mutate_at(cols, factor)
factor(df_slope$night, order=TRUE,
       levels= c("1", "2", "3", "4", "5", "6", "7", "8"))

```

# 1. lmes
```{r}
df_REM <- df_slope_week %>%
  filter(state == "phasic" | state == "tonic")

fit.REM_exp30to45 <-  lmer(exp30to45 ~ night + channel + night*state + night:condition + condition:channel + state:night:condition + order +tst + exp30to45_baseline + (1|participant), data=df_REM)
anova.REM_exp30to45 <- anova(fit.REM_exp30to45)

# estimated means
REM_exp30to45.esmmeans <- estimate_means(fit.REM_exp30to45 , by = c("state", "night", "condition"))
```
#2. posthoc
```{r}
pairs(emmeans(fit.REM_exp30to45, ~night:state:condition), simple="condition", p.adjust = "tukey")
contrast(emmeans(fit.REM_exp30to45, ~ night * condition | state), method = "trt.vs.ctrl", ref = 1, p.adjust = "sidak")
```
#3. Plot
```{r}
# exp 30 to 45Hz 
exp30to45_REM_week <- ggplot(REM_exp30to45.esmmeans, aes(x = night, y = Mean, linetype=condition, colour=state, shape=condition, group=condition)) +
     facet_grid(~state) +
 geom_line() +
     geom_errorbar(aes(x=night, y=Mean, ymin=Mean-SE, ymax=Mean+SE,), linetype=1, width=0.4, lwd=0.3, position = position_dodge(0.3)) +
  geom_point(aes(colour=state),fill="white", size=2, position = position_dodge(0.3)) +
  theme_prism(base_size = 10, base_fontface="plain", base_line_size=0.2) +
  scale_y_continuous(limits = c(-3.8, -3.4), breaks = seq(-3.8, -3.4, 0.08), expand = c(0, NA))+
  scale_x_discrete(labels=c("B", "1", "2", "3", "4", "5", "6", "7")) +
  scale_colour_manual(values = c("phasic" = "#0072B2", "tonic" = "#D55E00")) + 
    scale_shape_manual(values = c(16,21)) +
  ylab(expression("spectral slope 30-45 Hz "~(mu*V^2/Hz))) +
  theme(legend.position="none") 

```

