---
title: "within night dynamics"
output: html_notebook
---

# 1. Import functions
```{r}
library(devtools)
library(lmerTest)
library(lme4)
library(emmeans)
library(tidyverse)
library(broom)
library(kableExtra)
library(ggpubr)
library(ggprism)
```
# 2. Load dataset (for Fig 1, S6)
```{r}
df_clean <- read_csv("data/for paper/duration/df_week.csv", show_col_types = FALSE)

cols <- c("participant", "condition", "night", "order", "cycle","channel")
df_clean <- df_clean %>% mutate_at(cols, factor)
factor(df_clean$night, order=TRUE,
       levels= c("1", "2", "3", "4", "5", "6", "7", "8", "9"))
factor(df_clean$cycle, order=TRUE,
       levels= c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10"))

```
#3. Phasic and tonic probability changes (Fig 1)
```{r}
df_baseline<- df_clean %>%
  filter(night == "1") %>% 
  filter(!cycle=="5" &!cycle=="6"& !cycle=="7"& !cycle=="8" & !cycle=="9" & !cycle=="10")

# cycle 1-4 chosen based on levels of distibution 
#ggplot(df_baseline, aes(x = prob_tonic_cycles,)) +
#  geom_histogram(binwidth = 1, fill = "skyblue", color = "black") +
#  facet_wrap(~cycle, ncol = 10) +
#  labs(
#    title = "Distribution of Values Across Cycles",
#    x = "Value",
#    y = "Count"
#  ) +
#  theme_minimal()

fit.baseline_phasicprob <- lmer(prob_phasic_cycles ~ cycle*channel + condition + tst + order + (1|participant), data=df_baseline)
anova.baseline_phasicprob  <-  anova(fit.baseline_phasicprob)
esmmeans_baseline_phasicprob <- estimate_means(fit.baseline_phasicprob, by = c("cycle"))
contrast((emmeans(fit.baseline_phasicprob, ~ cycle)), method = "trt.vs.ctrl", ref = 1, adjust = "sidak")

fit.baseline_tonicprob <- lmer(prob_tonic_cycles ~ cycle*channel + condition + tst + order + (1|participant), data=df_baseline)
anova.baseline_tonicprob  <-  anova(fit.baseline_tonicprob)
esmmeans_baseline_tonicprob <- estimate_means(fit.baseline_tonicprob, by = c("cycle"))

##
df_SE <- df_clean %>%
  filter(condition=="SE") %>% 
  filter(!night == "1") %>% 
  filter(!cycle=="5" &!cycle=="6"& !cycle=="7"& !cycle=="8" & !cycle=="9" & !cycle=="10")

# cycle 1-4 chosen based on levels of distibution 
#ggplot(df_baseline, aes(x = prob_tonic_cycles,)) +
#  geom_histogram(binwidth = 1, fill = "skyblue", color = "black") +
#  facet_wrap(~cycle, ncol = 10) +
#  labs(
#    title = "Distribution of Values Across Cycles",
#    x = "Value",
#    y = "Count"
#  ) +
#  theme_minimal()


fit.SE_tonicprob <- lmer(prob_tonic_cycles ~ cycle*channel*night + tst + order + (1|participant), data=df_SE)
anova.baseline_tonicprob  <-  anova(fit.SE_tonicprob)
esmmeans_SE_tonicprob <- estimate_means(fit.SE_tonicprob, by = c("cycle"))

fit.SE_phasicprob <- lmer(prob_phasic_cycles ~ cycle*channel*night + tst + order + (1|participant), data=df_SE)
anova.baseline_phasicprob  <-  anova(fit.SE_phasicprob)
esmmeans_SE_phasicprob <- estimate_means(fit.SE_phasicprob, by = c("cycle"))

df_SR <- df_clean %>%
  filter(condition=="SR") %>% 
  filter(!night == "1") %>% 
  filter(!cycle=="5" &!cycle=="6"& !cycle=="7"& !cycle=="8" & !cycle=="9" & !cycle=="10")

fit.SR_tonicprob <- lmer(prob_tonic_cycles ~ cycle*channel*night + tst + order + (1|participant), data=df_SR)
anova.SR_tonicprob  <-  anova(fit.SR_tonicprob)
esmmeans_SR_tonicprob <- estimate_means(fit.SR_tonicprob, by = c("cycle"))
contrast((emmeans(fit.SR_tonicprob, ~ cycle)), method = "trt.vs.ctrl", ref = 1, adjust = "sidak")

fit.SR_phasicprob <- lmer(prob_phasic_cycles ~ cycle*channel*night + tst + order + (1|participant), data=df_SR)
anova.baseline_phasicprob  <-  anova(fit.SE_phasicprob)
esmmeans_SR_phasicprob <- estimate_means(fit.SR_phasicprob, by = c("cycle"))

# Plot
baseline_phasic <- ggplot(esmmeans_baseline_phasicprob, aes(x = cycle, y = Mean, group=1)) +
geom_line(linewidth=0.3, colour= "#0072B2") +
geom_errorbar(aes(x=cycle, y=Mean, ymin=Mean-SE, ymax=Mean+SE,), colour= "#0072B2", width=0.4, lwd=0.3) +
 geom_point(shape = 16, size = 2, colour= "#0072B2") +
  labs(
    x = "REM cycle",
    y = "percentage (%)",
    shape = "Stage"
  ) +
 scale_y_continuous(limits = c(0, 0.14), breaks = seq(0,0.14,0.02), expand = c(0, NA)) +
 theme_prism(base_size = 10, base_fontface="plain", base_line_size=0.2) 

SE_phasic <- ggplot(esmmeans_SE_phasicprob, aes(x = cycle, y = Mean, group=1)) +
geom_line(linewidth=0.3, colour= "#0072B2") +
geom_errorbar(aes(x=cycle, y=Mean, ymin=Mean-SE, ymax=Mean+SE,), colour= "#0072B2", width=0.4, lwd=0.3) +
 geom_point(shape = 16, size = 2, colour= "#0072B2") +
  labs(
    x = "REM cycle",
    y = "percentage (%)",
    shape = "Stage"
  ) +
 scale_y_continuous(limits = c(0, 0.14), breaks = seq(0,0.14,0.02), expand = c(0, NA)) +
 theme_prism(base_size = 10, base_fontface="plain", base_line_size=0.2) 

SR_phasic <- ggplot(esmmeans_SR_phasicprob, aes(x = cycle, y = Mean, group=1)) +
geom_line(linewidth=0.3, colour= "#0072B2") +
geom_errorbar(aes(x=cycle, y=Mean, ymin=Mean-SE, ymax=Mean+SE,), colour= "#0072B2", width=0.4, lwd=0.3) +
 geom_point(fill="white", shape = 21, size = 2, colour= "#0072B2") +
  labs(
    x = "REM cycle",
    y = "percentage (%)",
    shape = "Stage"
  ) +
 scale_y_continuous(limits = c(0, 0.14), breaks = seq(0,0.14,0.02), expand = c(0, NA)) +
 theme_prism(base_size = 10, base_fontface="plain", base_line_size=0.2) 

baseline_tonic <- ggplot(esmmeans_baseline_tonicprob, aes(x = cycle, y = Mean, group=1)) +
geom_line(linewidth=0.3, colour= "#D55E00") +
geom_errorbar(aes(x=cycle, y=Mean, ymin=Mean-SE, ymax=Mean+SE,), colour= "#D55E00", width=0.4, lwd=0.3) +
 geom_point(shape = 16, size = 2, colour= "#D55E00") +
  labs(
    x = "REM cycle",
    y = "percentage (%)",
    shape = "Stage"
  ) +
 scale_y_continuous(limits = c(0.85, 1), breaks = seq(0.8,1.0,0.05), expand = c(0, NA)) +
 theme_prism(base_size = 10, base_fontface="plain", base_line_size=0.2) 

SE_tonic <- ggplot(esmmeans_SE_tonicprob, aes(x = cycle, y = Mean, group=1)) +
geom_line(linewidth=0.3, colour= "#D55E00") +
geom_errorbar(aes(x=cycle, y=Mean, ymin=Mean-SE, ymax=Mean+SE,), colour= "#D55E00", width=0.4, lwd=0.3) +
 geom_point(shape = 16, size = 2, colour= "#D55E00") +
  labs(
    x = "REM cycle",
    y = "percentage (%)",
    shape = "Stage"
  ) +
 scale_y_continuous(limits = c(0.85, 1), breaks = seq(0.8,1.0,0.05), expand = c(0, NA)) +
 theme_prism(base_size = 10, base_fontface="plain", base_line_size=0.2) 

SR_tonic <- ggplot(esmmeans_SR_tonicprob, aes(x = cycle, y = Mean, group=1)) +
geom_line(linewidth=0.3, colour= "#D55E00") +
geom_errorbar(aes(x=cycle, y=Mean, ymin=Mean-SE, ymax=Mean+SE,), colour= "#D55E00", width=0.4, lwd=0.3) +
 geom_point(fill="white", shape = 21, size = 2, colour= "#D55E00") +
  labs(
    x = "REM cycle",
    y = "percentage (%)",
    shape = "Stage"
  ) +
  scale_y_continuous(limits = c(0.85, 1), breaks = seq(0.8,1.0,0.05), expand = c(0, NA)) +
 theme_prism(base_size = 10, base_fontface="plain", base_line_size=0.2) 
```
#4. Periodic and aperiodic components (Fig S6)
```{r}
df_baseline<- df_clean %>%
  filter(night == "1") %>% 
  filter(!cycle=="5" &!cycle=="6"& !cycle=="7"& !cycle=="8" & !cycle=="9" & !cycle=="10")

# change phasic or tonic
# exponent
fit.baseline_exp30to45 <- lmer(exponent_30_45_allcycles_tonic ~ cycle*channel + condition + tst  + (1|participant), data=df_baseline)
anova.baseline_exp30to45  <-  anova(fit.baseline_exp30to45)

# alpha
fit.baseline_IAPF <- lmer(IAPF_allcycles_tonic ~ cycle*channel + condition + tst + (1|participant), data=df_baseline)
anova.baseline_IAPF  <-  anova(fit.baseline_IAPF)
fit.baseline_snralpha <- lmer(snr_alpha_cycles_tonic ~ cycle*channel + condition + tst + (1|participant), data=df_baseline)
anova.baseline_snralpha <-  anova(fit.baseline_snralpha)

# theta
fit.baseline_densitytheta <- lmer(den_theta_cycles_tonic ~ cycle*channel + condition + tst + (1|participant), data=df_baseline)
anova.baseline_densitytheta  <-  anova(fit.baseline_densitytheta) #%>% select(c(5,6))

# estimated means
esmmeans_baseline_exp30to45 <- estimate_means(fit.baseline_exp30to45 , by = c("cycle"))
esmmeans_baseline_IAPF <- estimate_means(fit.baseline_IAPF , by = c("cycle"))
esmmeans_baseline_snralpha <- estimate_means(fit.baseline_snralpha , by = c("cycle"))
esmmeans_baseline_densitytheta <- estimate_means(fit.baseline_densitytheta , by = c("cycle"))

# Posthoc
contrast((emmeans(fit.baseline_exp30to45, ~ cycle)), method = "trt.vs.ctrl", ref = 1, adjust = "sidak")

```

