---
title: "to produce table from raw data for statistical analysis - PANAS"
output: html_notebook
---

# Import functions 
```{r}
library(lmerTest)
library(emmeans)
library(sjstats)
library(tidyverse)
library(broom)
library(devtools)
library(dplyr)
```
## --- to produce df_PANAS (baseline stats) ---
# Load raw data 
```{r}
df <- read_csv("PANAS_all_postsleepaffect_22Dec25.csv", show_col_types = FALSE) 

cols <- c("participant", "gender", "condition", "test_no", "day", "night", "panas_type", "order")
df <- df %>% mutate_at(cols, factor) 

```
# Append baseline PANAS to df
```{r}
df_baseline <- df %>% 
  group_by(day,panas_type,condition) %>% 
  nest() 

neg_SE_base <- pluck(df_baseline$data[[1]]) %>% dplyr::select(c(4)) #select PANAS score
neg_SR_base <- pluck(df_baseline$data[[9]]) %>% dplyr::select(c(4))
pos_SE_base <- pluck(df_baseline$data[[17]]) %>% dplyr::select(c(4))
pos_SR_base <- pluck(df_baseline$data[[25]]) %>% dplyr::select(c(4))

a <- cbind(df_baseline[[4]][[1]], neg_SE_base)
b <- cbind(df_baseline[[4]][[2]], neg_SE_base)
c <- cbind(df_baseline[[4]][[3]], neg_SE_base)
d <- cbind(df_baseline[[4]][[4]], neg_SE_base)
e <- cbind(df_baseline[[4]][[5]], neg_SE_base)
f <- cbind(df_baseline[[4]][[6]], neg_SE_base)
g <- cbind(df_baseline[[4]][[7]], neg_SE_base)
h <- cbind(df_baseline[[4]][[8]], neg_SE_base)
i <- cbind(df_baseline[[4]][[9]], neg_SR_base)
j <- cbind(df_baseline[[4]][[10]], neg_SR_base)
k <- cbind(df_baseline[[4]][[11]], neg_SR_base)
l <- cbind(df_baseline[[4]][[12]], neg_SR_base)
m <- cbind(df_baseline[[4]][[13]], neg_SR_base)
n <- cbind(df_baseline[[4]][[14]], neg_SR_base)
o <- cbind(df_baseline[[4]][[15]], neg_SR_base)
p <- cbind(df_baseline[[4]][[16]], neg_SR_base)
q <- cbind(df_baseline[[4]][[17]], pos_SE_base)
r <- cbind(df_baseline[[4]][[18]], pos_SE_base)
s <- cbind(df_baseline[[4]][[19]], pos_SE_base)
t <- cbind(df_baseline[[4]][[20]], pos_SE_base)
u <- cbind(df_baseline[[4]][[21]], pos_SE_base)
v <- cbind(df_baseline[[4]][[22]], pos_SE_base)
w <- cbind(df_baseline[[4]][[23]], pos_SE_base)
x <- cbind(df_baseline[[4]][[24]], pos_SE_base)
y <- cbind(df_baseline[[4]][[25]], pos_SR_base)
z <- cbind(df_baseline[[4]][[26]], pos_SR_base)
aa <- cbind(df_baseline[[4]][[27]], pos_SR_base)
ab <- cbind(df_baseline[[4]][[28]], pos_SR_base)
ac <- cbind(df_baseline[[4]][[29]], pos_SR_base)
ad <- cbind(df_baseline[[4]][[30]], pos_SR_base)
ae <- cbind(df_baseline[[4]][[31]], pos_SR_base)
af <- cbind(df_baseline[[4]][[32]], pos_SR_base)

baseline_PANAS <- rbind(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,
                     aa,ab,ac,ad,ae,af)

df_baseline <- df_baseline %>% 
  unnest(data) %>% 
  dplyr::select(c(1:3)) 

df_extend <- cbind(df_baseline,baseline_PANAS)
colnames(df_extend)[515] <- "baseline_PANAS"
colnames(df_extend)[7] <- "PANAS_score"

df_extend <- df_extend  %>%  relocate(baseline_PANAS, .after = PANAS_score)

df_extend <- df_extend %>%
  filter(!day == "9")

rm(list = ls()[-match(c("df_extend", "df"), ls())])
```
# For data that have channels: 
```{r}
df_reshape <- df_extend %>% 
  pivot_longer(
    cols =  c(28:515),
    names_to = c("measure", "state", "channel"),
    names_sep="_"
  ) %>% 
  unite("measure_state", measure, state, sep = "_") %>% 
  pivot_wider(
    names_from = measure_state,  # Use measure_state values as new column names
    values_from = value          # Fill these new columns with the values from the 'value' column
  )

cols <- c("participant", "gender", "condition", "test_no", "day", "night", "panas_type", "channel", "order")
df_reshape <- df_reshape %>% mutate_at(cols, factor) 

#saveRDS(df_reshape, "C:/Users/vj0005/OneDrive - University of Surrey/Documents/Papers/AFREM/R_stats/PANAS/to produce table for #stats/df_PANAS_22Dec.rds")

```
## --- to produce df_PANAS_week (baseline stats) ---
# SE/SR week - append baseline values 
```{r}
# extract baseline values for all variables 
baseline_values <-df_reshape %>% 
  filter(day == "2") %>% #postsleep
  group_by(day, panas_type, condition) %>% 
  nest() 

neg_SE_base <- pluck(baseline_values$data[[1]]) %>% dplyr::select(c(9:147))  
colnames(neg_SE_base) <- paste(colnames(neg_SE_base), 'baseline', sep = '_')
neg_SR_base <- pluck(baseline_values$data[[2]]) %>% dplyr::select(c(9:147))
colnames(neg_SR_base) <- paste(colnames(neg_SR_base), 'baseline', sep = '_')
pos_SE_base <- pluck(baseline_values$data[[3]]) %>% dplyr::select(c(9:147))
colnames(pos_SE_base) <- paste(colnames(pos_SE_base), 'baseline', sep = '_')
pos_SR_base <- pluck(baseline_values$data[[4]]) %>% dplyr::select(c(9:147))
colnames(pos_SR_base) <- paste(colnames(pos_SR_base), 'baseline', sep = '_')

df_PANAS_temp <- df_reshape %>% 
  group_by(day,panas_type, condition) %>% 
  nest()

a <- cbind(df_PANAS_temp[[4]][[1]], neg_SE_base)
b <- cbind(df_PANAS_temp[[4]][[2]], neg_SE_base)
c <- cbind(df_PANAS_temp[[4]][[3]], neg_SE_base)
d <- cbind(df_PANAS_temp[[4]][[4]], neg_SE_base)
e <- cbind(df_PANAS_temp[[4]][[5]], neg_SE_base)
f <- cbind(df_PANAS_temp[[4]][[6]], neg_SE_base)
g <- cbind(df_PANAS_temp[[4]][[7]], neg_SE_base)
h <- cbind(df_PANAS_temp[[4]][[8]], neg_SR_base)
i <- cbind(df_PANAS_temp[[4]][[9]], neg_SR_base)
j <- cbind(df_PANAS_temp[[4]][[10]], neg_SR_base)
k <- cbind(df_PANAS_temp[[4]][[11]], neg_SR_base)
l <- cbind(df_PANAS_temp[[4]][[12]], neg_SR_base)
m <- cbind(df_PANAS_temp[[4]][[13]], neg_SR_base)
n <- cbind(df_PANAS_temp[[4]][[14]], neg_SR_base)
o <- cbind(df_PANAS_temp[[4]][[15]], pos_SE_base)
p <- cbind(df_PANAS_temp[[4]][[16]], pos_SE_base)
q <- cbind(df_PANAS_temp[[4]][[17]], pos_SE_base)
r <- cbind(df_PANAS_temp[[4]][[18]], pos_SE_base)
s <- cbind(df_PANAS_temp[[4]][[19]], pos_SE_base)
t <- cbind(df_PANAS_temp[[4]][[20]], pos_SE_base)
u <- cbind(df_PANAS_temp[[4]][[21]], pos_SE_base)
v <- cbind(df_PANAS_temp[[4]][[22]], pos_SR_base)
w <- cbind(df_PANAS_temp[[4]][[23]], pos_SR_base)
x <- cbind(df_PANAS_temp[[4]][[24]], pos_SR_base)
y <- cbind(df_PANAS_temp[[4]][[25]], pos_SR_base)
z <- cbind(df_PANAS_temp[[4]][[26]], pos_SR_base)
aa <- cbind(df_PANAS_temp[[4]][[27]], pos_SR_base)
ab <- cbind(df_PANAS_temp[[4]][[28]], pos_SR_base)

baseline_values <- rbind(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,aa,ab)

df_PANAS_temp <- df_reshape %>% 
  dplyr::select(c(1:3)) 

df_PANAS <- cbind(df_PANAS_temp,baseline_values) 

saveRDS(df_PANAS, "C:/Users/vj0005/OneDrive - University of Surrey/Documents/Papers/AFREM/R_stats/PANAS/to produce table for stats/df_PANAS_week_22Dec.rds")
```
