---
title: "triplets excitability"
output: html_notebook
---

#Import functions
```{r}
library(devtools)
library(lmerTest)
library(lme4)
library(emmeans)
library(tidyverse)
library(broom)
library(kableExtra)
library(ggpubr)
library(ggprism)
```

#1. Load dataset (Fig S8)
```{r}
df <- read_csv("data/for paper/excitability/triplet/df_triplet_baseline.csv", show_col_types = FALSE)

cols <- c("participant", "condition", "night", "order", "channel")
df <- df  %>% mutate_at(cols, factor)
factor(df$night, order=TRUE,
       levels= c("1", "2", "3", "4", "5", "6", "7", "8", "9"))
```
#2. lmes
```{r}
df_baseline <- df %>% filter(night=="1") %>% 
  dplyr::select(c(1:5,7,24:31))

df_baseline <- df_baseline %>% 
  pivot_longer(
  cols = c(7:14), 
    names_to = c(".value", "NREM"),
    names_pattern = "(.+)_(pre|post)"
)

fit.baseline_NREM30to45 <- lmer(exponent_30_45
 ~ channel + order + NREM + tst + (1|participant), data=df_baseline)
anova.fitbaseline_NREM30to45 <- anova(fit.baseline_NREM30to45)

# estimated means
baseline_NREM30to45_esmmeans <- estimate_means(fit.baseline_NREM30to45 , by = c("NREM"))
```
#3. Baseline: plot (baseline)
```{r}
library(gghalves)
df_baseline_average <- df_baseline %>% ungroup() %>% 
  dplyr::select(!c(2:6)) %>% 
  group_by(participant, NREM) %>% 
  dplyr::summarise(across(everything(), mean, na.rm=TRUE))

df_baseline_average$NREM <- factor(df_baseline_average$NREM, levels = c("pre", "post"))

plot_baseline_NREM30to45 <- ggplot(df_baseline_average, aes(x = NREM, y = exponent_30_45, fill = NREM)) +
  # Left half violin for first
  geom_half_violin(data = subset(df_baseline_average, NREM == "pre"),side = "l",  # <-- flip to left
 alpha = 0.8, trim = FALSE, position = position_nudge(x = -0.1)) +
# Right half violin for last
  geom_half_violin(data = subset(df_baseline_average, NREM == "post"),side = "r", alpha = 0.8, trim = FALSE, position = position_nudge(x = 0.1)) +
# join same participants with line across state
   geom_line(aes(group = participant), colour = "black", linewidth = 0.3, alpha = 0.2, position = position_jitter(width = 0.05, seed = 123)) +
  geom_point(aes(shape = NREM, colour=NREM), size=1, position = position_jitter(width = 0.05, seed = 123)) +
 scale_fill_manual(values = c("pre" = "#009E73", "post" = "#CC79A7")) + 
  scale_colour_manual(values = c("pre" = "#009E73", "post" = "#CC79A7")) + 
  scale_shape_manual(values = c(21,21)) +
  scale_y_continuous(limits = c(-5, -1.5), breaks = seq(-5, -1.5,0.5), expand = c(0, NA)) + # set scales to begin at , intervals of 3 until highest value , expand prevents padding at top and bottom of y axis so it will be in line with x axis
   ylab("NREM spectral slope 30 - 45 Hz" ~(mu*V^2/Hz)) + 
  theme_prism(base_size = 10, base_fontface="plain", base_line_size=0.2) +
  theme(legend.position = "none") 

plot_baseline_NREM30to45 <- plot_baseline_NREM30to45 +
   geom_errorbar(data = subset(baseline_NREM30to45_esmmeans, NREM == "pre"), aes(x=NREM, y=Mean, ymin=Mean-SE, ymax=Mean+SE), width=0.1, lwd=0.5, position = position_nudge(x = -0.2)) +
    geom_point(data = subset(baseline_NREM30to45_esmmeans, NREM == "pre"), aes(x=NREM, y=Mean, shape=NREM, colour=NREM), fill="#009E73", colour="black", size =2,  position = position_nudge(x = -0.2)) +
   # add error bar and mean for tonic (esmmeans)
    geom_errorbar(data = subset(baseline_NREM30to45_esmmeans, NREM == "post"), aes(x=NREM, y=Mean, ymin=Mean-SE, ymax=Mean+SE), width=0.1, lwd=0.5, position = position_nudge(x = 0.2)) +
    geom_point(data = subset(baseline_NREM30to45_esmmeans, NREM == "post"), aes(x=NREM, y=Mean, shape=NREM, colour=NREM),colour="black", size =2,  position = position_nudge(x = 0.2))  +
 # geom_line(data = baseline_ITPF_state_esmmeans, aes(x=state, y=Mean, group=1), colour = "black", linewidth = 1) +
  scale_x_discrete(name = NULL) 
```
#4. append baseline values
```{r}
keep_vars <- c("df", "df_all")
rm(list = setdiff(ls(), keep_vars))

baseline_values <- df %>% 
  filter(night == "1") %>% 
  group_by(condition) %>% 
  nest() %>% 
  nest_rename_with(data, .fn = function(.x){paste0(.x,"_baseline")}, .cols=c(7:75)) %>% 
     nest_slice(data, 
              rep(1:n(), times = 9)) 
              
df_temp <- df %>% 
  group_by(condition) %>% 
  nest() %>% 
  nest_arrange(data, night)

# ---
df_temp[[2]][[1]] <- cbind(df_temp[[2]][[1]],baseline_values[[2]][[1]])
df_temp[[2]][[2]] <- cbind(df_temp[[2]][[2]],baseline_values[[2]][[2]])

#---
df_temp <- unnest(df_temp) %>% 
  ungroup()
####

df_week <- df_temp %>%  
  filter(!night=="9") %>% 
  select(c(1:5,7,24:31))

df_week_baseline <- df_temp %>%  
  filter(!night=="9") %>% 
  select(c(1:5,7,99:106))
  
df_week <- df_week %>%  pivot_longer(
  cols = c(7:14), 
    names_to = c(".value", "time"),
    names_pattern = "(.+)_(pre|post)"
)

df_week_baseline <- df_week_baseline %>%  pivot_longer(
  cols = c(7:14), 
    names_to = c(".value", "time"),
    names_pattern = "^(.*)_(pre|post)_baseline$"
) %>%
  rename_with(
    .cols = c(8:11),   # <-- replace with your actual column names
    .fn = ~ paste0(.x, "_baseline")
  ) %>% 
  select(c(8:11))

df_week_long <- cbind(df_week, df_week_baseline)

cols <- c("participant", "condition", "night", "order", "channel", "time")
df_week_long <- df_week_long  %>% mutate_at(cols, factor)
```
#5. Week: lmes and plot
```{r}
df_week_SE <- df_week_long %>%  
  filter(condition=="SE")

df_week_SR <- df_week_long %>%  
  filter(condition=="SR")

# NREM
#SE
fit.week_NREM30to45_SE <- lmer(exponent_30_45
 ~ night*time + channel + exponent_30_45_baseline + tst + order + (1|participant), data=df_week_SE)
anova.fitweek_NREM30to45_SE <- anova(fit.week_NREM30to45_SE)

#SR
fit.week_NREM30to45_SR <- lmer(exponent_30_45
 ~ night*time + channel + exponent_30_45_baseline + tst + order + (1|participant), data=df_week_SR)
anova.fitweek_NREM30to45_SR <- anova(fit.week_NREM30to45_SR)

# Plot ----
# SE
exp30to45_prepost_SE_esmmeans <- estimate_means(fit.week_NREM30to45_SE , by = c( "time"))
exp30to45_prepost_SR_esmmeans <- estimate_means(fit.week_NREM30to45_SR , by = c( "time"))


library(gghalves)
# Average for visualisation
df_week_average_SE <- df_week_SE %>% ungroup() %>% 
  dplyr::select(c(2,7,8:15)) %>% #participant, time , variables
  group_by(participant, time) %>% 
  dplyr::summarise(across(everything(), mean, na.rm=TRUE))

df_week_average_SR <- df_week_SR %>% ungroup() %>% 
  dplyr::select(c(2,7,8:15)) %>% #participant, time , variables
  group_by(participant, time) %>% 
  dplyr::summarise(across(everything(), mean, na.rm=TRUE))

plot_NREM30to45_prepost <- ggplot(df_week_average_SR, aes(x = time, y = exponent_30_45, fill = time)) +
  # Left half violin for pre
  geom_half_violin(data = subset(df_week_average_SR, time == "pre"),side = "l",  # <-- flip to left
 alpha = 0.8, trim = FALSE, position = position_nudge(x = -0.1)) +
# Right half violin for post
  geom_half_violin(data = subset(df_week_average_SR, time == "post"), side = "r", alpha = 0.8, trim = FALSE, position = position_nudge(x = 0.1)) +
# join same participants with line across state
   geom_line(aes(group = participant), colour = "black", linewidth = 0.3, alpha = 0.2, position = position_jitter(width = 0.05, seed = 123)) +
  geom_point(aes(shape = time, colour=time), size=1, position = position_jitter(width = 0.05, seed = 123)) +
 scale_fill_manual(values = c("pre" = "#009E73", "post" = "#CC79A7")) + 
  scale_colour_manual(values = c("pre" = "#009E73", "post" = "#CC79A7")) + 
  scale_shape_manual(values = c(1,1)) +
  scale_y_continuous(limits = c(-5, -1.5), breaks = seq(-5, -1.5,0.5), expand = c(0, NA)) + # set scales to begin at , intervals of 3 until highest value , expand prevents padding at top and bottom of y axis so it will be in line with x axis
   ylab("spectral slope" ~(mu*V^2/Hz)) + 
  theme_prism(base_size = 6, base_fontface="plain", base_line_size=0.2) +
  theme(legend.position = "none") 

plot_NREM30to45_prepost <- plot_NREM30to45_prepost +
  # error bar and average for "first"
   geom_errorbar(data = subset(exp30to45_prepost_SR_esmmeans, time == "pre"), aes(x=time, y=Mean, ymin=Mean-SE, ymax=Mean+SE), width=0.1, lwd=0.2, position = position_nudge(x = -0.2)) +
    geom_point(data = subset(exp30to45_prepost_SR_esmmeans, time == "pre"), aes(x=time, y=Mean, colour=time), fill="#009E73", shape=21, colour="black", size =1, stroke=0.2,  position = position_nudge(x = -0.2)) +
    # error bar and average for "last"
    geom_errorbar(data = subset(exp30to45_prepost_SR_esmmeans, time == "post"), aes(x=time, y=Mean, ymin=Mean-SE, ymax=Mean+SE), width=0.1, lwd=0.2, position = position_nudge(x = 0.2)) +
    geom_point(data = subset(exp30to45_prepost_SR_esmmeans, time == "post"), aes(x=time, y=Mean, colour=time), fill="#CC79A7", shape=21, colour="black", size =1,stroke=0.2,   position = position_nudge(x = 0.2))  +
 # geom_line(data = baseline_ITPF_state_esmmeans, aes(x=state, y=Mean, group=1), colour = "black", linewidth = 1) +
  scale_x_discrete(name = NULL) 

```

## Associations (prepost diff) with slope/theta/alpha
#1. Load dataset 
```{r}
df <- read_csv("data/for paper/excitability/triplet/df_week_slopediff_3.csv", show_col_types = FALSE)

cols <- c("participant", "condition", "night", "order", "channel")
df <- df  %>% mutate_at(cols, factor)
factor(df$night, order=TRUE,
       levels= c("1", "2", "3", "4", "5", "6", "7", "8", "9"))
```
#2. Baseline lmes
```{r}
df_baseline <- df %>%
  filter(night == "1")

df_baseline <- df_baseline %>%  
  mutate(m_exponent_30_45_prepost_diff_z = scale(m_exponent_30_45_prepost_diff)) %>% 
  mutate(m_exponent_30_45_between_phasic_z = scale(m_exponent_30_45_between_phasic)) %>% 
  mutate(m_exponent_30_45_between_tonic_z = scale(m_exponent_30_45_between_tonic)) %>% 
  mutate(snr_alpha_between_phasic_z = scale(snr_alpha_between_phasic)) %>% 
  mutate(snr_alpha_between_tonic_z = scale(snr_alpha_between_tonic)) %>% 
  mutate(den_theta_between_phasic_z = scale(den_theta_between_phasic)) %>% 
  mutate(den_theta_between_tonic_z = scale(den_theta_between_tonic)) %>%
  mutate(IAPF_between_phasic_z = scale(IAPF_between_phasic)) %>% 
  mutate(IAPF_between_tonic_z = scale(IAPF_between_tonic))

fit.phasicbaseline_exp30to45 <- lmer(m_exponent_30_45_prepost_diff_z
 ~ m_exponent_30_45_between_phasic_z + channel + order + scale(tst) + (1|participant), data=df_baseline)
phasicslope_summary <- as.data.frame(coef(summary(fit.phasicbaseline_exp30to45))) 
phasicslope_summary <- phasicslope_summary[2,]

fit.phasicbaseline_snralpha <- lmer(m_exponent_30_45_prepost_diff_z
 ~ snr_alpha_between_phasic_z + channel + order + scale(tst) + (1|participant), data=df_baseline)
phasic_snralpha_summary <- as.data.frame(coef(summary(fit.phasicbaseline_snralpha))) 
phasic_snralpha_summary <- phasic_snralpha_summary[2,]

fit.phasicbaseline_dentheta <- lmer(m_exponent_30_45_prepost_diff_z
 ~ den_theta_between_phasic_z + channel + order + scale(tst) + (1|participant), data=df_baseline)
phasic_dentheta_summary <- as.data.frame(coef(summary(fit.phasicbaseline_dentheta))) 
phasic_dentheta_summary <- phasic_dentheta_summary[2,]

##
fit.tonicbaseline_exp30to45 <- lmer(m_exponent_30_45_prepost_diff_z
 ~ m_exponent_30_45_between_tonic_z + channel + order + scale(tst) + (1|participant), data=df_baseline)
tonicslope_summary <- as.data.frame(coef(summary(fit.tonicbaseline_exp30to45))) 
toniccslope_summary <- tonicslope_summary[2,]

fit.tonicbaseline_snralpha <- lmer(m_exponent_30_45_prepost_diff_z
 ~ snr_alpha_between_tonic_z + channel + order + scale(tst) + (1|participant), data=df_baseline)
tonic_snralpha_summary <- as.data.frame(coef(summary(fit.tonicbaseline_snralpha))) 
tonic_snralpha_summary <- tonic_snralpha_summary[2,]

fit.tonicbaseline_dentheta <- lmer(m_exponent_30_45_prepost_diff_z
 ~ den_theta_between_tonic_z + channel + order + scale(tst) + (1|participant), data=df_baseline)
tonic_dentheta_summary <- as.data.frame(coef(summary(fit.tonicbaseline_dentheta))) 
tonic_dentheta_summary <- tonic_dentheta_summary[2,]

results_adj <- rbind(phasicslope_summary, phasic_dentheta_summary, phasic_snralpha_summary, toniccslope_summary, tonic_dentheta_summary, tonic_snralpha_summary) 
colnames(results_adj)[5] <- "pvalue"
results_adj <- results_adj %>%
  mutate(adj_pvalue = p.adjust(pvalue, method = "fdr"))
```
#3. Plot (baseline FigS8)
```{r}
ordinary_residuals <- residuals(fit.tonicbaseline_dentheta) # change model accordingly
coeff_of_interest <- as.numeric(fixef(fit.tonicbaseline_dentheta)["den_theta_between_tonic_z"])
predictor_values <- as.numeric(model.frame(fit.tonicbaseline_dentheta)$den_theta_between_tonic_z)
partial_residuals_calculated <- ordinary_residuals + coeff_of_interest * predictor_values
df_points_for_plot <- data.frame(
    x_variable = predictor_values,
    y_partial_residual = partial_residuals_calculated)
df_line <- as.data.frame(effects.fittonicbaseline_dentheta)

plot_corr <- ggplot(data = df_points_for_plot, aes(x = x_variable, y = y_partial_residual)) +
     # Add partial residual points
     geom_point(aes(color = x_variable), size = 0.5 * 2, shape=1, stroke=0.35) +
   #  scale_color_gradientn(colors = c("#0072B2", "#8bd5ff", "#008bd9", "#8bd5ff", "#0072B2", "#8bd5ff")) +
     scale_color_gradientn(colors = c("#FF7a11","#FFbc87", "#FF9038","#FFa65F", "#FF7a11", "#FFbc87")) +
     # Add the fitted line
     geom_line(data = df_line, aes(x = den_theta_between_tonic_z, y = fit),
               color = "black", linewidth = 1) +
     # Add confidence interval ribbon
     geom_ribbon(data = df_line,
                 aes(x = den_theta_between_tonic_z, y=fit, ymin = lower, ymax = upper),
                 fill = "grey", alpha = 0.3) + # No 'y_partial_residual' should be here or implied
     labs(
        # x = expression("tonic spectral slope (z-scored)"),
         x="tonic theta density (z-scored)",
        # x="tonic alpha amplitude (z-scored)",
         y = expression("spectral slope change\nlast NREM-first NREM (z-scored)"),
         title = ""
     ) +
    scale_x_continuous(limits = c(-1.5, 1.5), breaks = seq(-1.5, 1.5, 0.5), expand = c(0, NA)) +
    scale_y_continuous(limits = c(-3, 3), breaks = seq(-3, 3, 1), expand = c(0, NA)) +
    theme_prism(base_size = 10, base_fontface="plain", base_line_size=0.2) +
    theme(legend.position = "none")
```
#4. Append baseline
```{r}
# Extract baseline values and append to original frame 
baseline_values <-df_all %>% 
  filter(night == "1") %>% 
  group_by(condition) %>% 
  nest() %>% 
  nest_rename_with(data, .fn = function(.x){paste0(.x,"_baseline")}, .cols=c(5:103)) %>% 
     nest_slice(data, 
              rep(1:n(), times = 9))
              
df_all_temp <- df_all %>% 
  group_by(condition) %>% 
  nest() %>% 
  nest_arrange(data, night)

# ---
df_all_temp[[2]][[1]] <- cbind(df_all_temp[[2]][[1]],baseline_values[[2]][[1]])
df_all_temp[[2]][[2]] <- cbind(df_all_temp[[2]][[2]],baseline_values[[2]][[2]])

#---
df_all <- unnest(df_all_temp) %>% 
  ungroup()
```
#5. Week: lmes and plots (Fig S8)
```{r}
# exp 30 to 45 ----
df_week_exp30to45 <- df_all %>% filter(!night=="9") %>% 
  dplyr::select(1:5 | contains("exponent_30_45")) %>% 
   pivot_longer(
    cols = c(10:13),
    names_to = "state_cycle",
    names_pattern = "m_exponent_30_45_cyc_(.*)",
    values_to = "exponent_cycle"
  ) %>% 
   pivot_longer(
    cols = c(11:13),
    names_to = "state_between",
    names_pattern = "m_exponent_30_45_between_(.*)",
    values_to = "exponent_between"
  )

cols <- c("participant", "condition", "night", "state_cycle", "state_between", "channel")
df_week_exp30to45 <- df_week_exp30to45  %>% mutate_at(cols, factor)

df_week_exp30to45_NREM <- df_week_exp30to45 %>%  filter(state_cycle =="nrem")
df_week_exp30to45_phasic <- df_week_exp30to45 %>%  filter(state_cycle =="phasic")
df_week_exp30to45_tonic <- df_week_exp30to45 %>%  filter(state_cycle =="tonic")


fit.NREMweek_exp30_45_prepost <- lmer(m_exponent_30_45_prepost_diff
 ~ night + channel + night:condition + condition:channel + m_exponent_30_45_prepost_diff_baseline + tst + (1|participant), data=df_week_exp30to45_NREM)
anova.fitNREMweek_prepost_exp30_45 <- anova(fit.NREMweek_exp30_45_prepost)

# Posthoc ----
pairs(emmeans(fit.NREMweek_exp30_45_prepost, ~night:condition, by="night", p.adjust = "tukey"))
#Perform contrasts comparing each level of night to the baseline (night == 1) separately by condition
contrast((emmeans(fit.week_exp30_45_firstlast, ~ night:condition)), method = "trt.vs.ctrl", ref = 1, adjust = "sidak") # as we assume baseline SE and SR as one, it compares all to SEnight1 (which is really the combo of both)

# Plot 
q2_exp30to45_NREMprepost_esmmeans <- estimate_means(fit.NREMweek_exp30_45_prepost , by = c( "night", "condition"))

NREM30to45_triplet <-ggplot(q2_exp30to45_NREMprepost_esmmeans, aes(x = night, y = Mean, shape=condition, group=condition, colour=condition)) +
  geom_line(position = position_dodge(0.3)) +
  geom_errorbar(aes(x=night, y=Mean, ymin=Mean-SE, ymax=Mean+SE,), linetype=1, width=0.4, lwd=0.3, position = position_dodge(0.3)) +
  geom_point(fill="white", size=2, position = position_dodge(0.3)) +
  #geom_point(aes(colour=condition),fill="white", size=2, position = position_dodge(0.3)) +
  theme_prism(base_size = 10, base_fontface="plain", base_line_size=0.2) +
  scale_y_continuous(limits = c(-1.1, -0.7), breaks = seq(-1.1, -0.7, 0.1), expand = c(0, NA)) +
  scale_x_discrete(labels=c("B", "1", "2", "3", "4", "5", "6", "7")) +
   scale_fill_manual(values = c("SE" = "#009E73B2", "SR" = "#009E73B2")) + 
  scale_colour_manual(values = c("SE" = "#009E73B2", "SR" = "#009E73B2")) + 
  xlab("night") +  ylab("spectral slope change\n(NREMpost - NREMpre") +
    scale_shape_manual(values = c(16,21)) +
   theme(legend.position="none") 
```
#6. Associations and plots (Fig S8)
```{r}
df_week <- df %>%
  filter(!night=="9")

df_week <- df_week %>%  
  mutate(m_exponent_30_45_prepost_diff_z = scale(m_exponent_30_45_prepost_diff)) %>% 
  mutate(m_exponent_30_45_between_phasic_z = scale(m_exponent_30_45_between_phasic)) %>% 
  mutate(m_exponent_30_45_between_tonic_z = scale(m_exponent_30_45_between_tonic)) %>% 
  mutate(snr_alpha_between_phasic_z = scale(log(snr_alpha_between_phasic))) %>% 
  mutate(snr_alpha_between_tonic_z = scale(log(snr_alpha_between_tonic))) %>% 
  mutate(den_theta_between_phasic_z = scale(den_theta_between_phasic)) %>% 
  mutate(den_theta_between_tonic_z = scale(den_theta_between_tonic)) %>% 
  mutate(IAPF_between_phasic_z = scale(IAPF_between_phasic)) %>% 
  mutate(IAPF_between_tonic_z = scale(IAPF_between_tonic))

fit.week_exp30to45_phasic <- lmer(m_exponent_30_45_prepost_diff_z
 ~ m_exponent_30_45_between_phasic_z + scale(m_exponent_30_45_between_phasic_baseline) + scale(m_exponent_30_45_prepost_diff_baseline) + channel +night + condition:night + scale(tst) + (1|participant), data=df_week)
phasicslope_summary <- as.data.frame(coef(summary(fit.week_exp30to45_phasic))) 
phasicslope_summary <- phasicslope_summary[2,]

fit.week_snralpha_phasic <- lmer(m_exponent_30_45_prepost_diff_z
 ~ snr_alpha_between_phasic_z + scale(snr_alpha_between_phasic_baseline) + scale(m_exponent_30_45_prepost_diff_baseline) + channel +night + condition:night + scale(tst) + (1|participant), data=df_week)
phasic_snralpha_summary <- as.data.frame(coef(summary(fit.week_snralpha_phasic))) 
phasic_snralpha_summary <- phasic_snralpha_summary[2,]

fit.week_dentheta_phasic <- lmer(m_exponent_30_45_prepost_diff_z
 ~ den_theta_between_phasic_z + scale(snr_alpha_between_phasic_baseline) + scale(m_exponent_30_45_prepost_diff_baseline) + channel +night + condition:night + scale(tst) + (1|participant), data=df_week)
phasic_dentheta_summary <- as.data.frame(coef(summary(fit.week_dentheta_phasic))) 
phasic_dentheta_summary <- phasic_dentheta_summary[2,]

##
fit.week_exp30to45_tonic <- lmer(m_exponent_30_45_prepost_diff_z
 ~ m_exponent_30_45_between_tonic_z + scale(m_exponent_30_45_prepost_diff_baseline) + channel +night + condition:night + scale(tst) + (1|participant), data=df_week)
tonicslope_summary <- as.data.frame(coef(summary(fit.week_exp30to45_tonic))) 
tonicslope_summary <- tonicslope_summary[2,]

fit.week_snralpha_tonic <- lmer(m_exponent_30_45_prepost_diff_z
 ~ snr_alpha_between_tonic_z + scale(snr_alpha_between_tonic_baseline) + scale(m_exponent_30_45_prepost_diff_baseline) + channel +night + condition:night + scale(tst) + (1|participant), data=df_week)
tonic_snralpha_summary <- as.data.frame(coef(summary(fit.week_snralpha_tonic))) 
tonic_snralpha_summary <- tonic_snralpha_summary[2,]

fit.week_dentheta_tonic <- lmer(m_exponent_30_45_prepost_diff_z
 ~ den_theta_between_tonic_z + scale(snr_alpha_between_tonic_baseline) + scale(m_exponent_30_45_prepost_diff_baseline) + channel +night + condition:night + scale(tst) + (1|participant), data=df_week)
tonic_dentheta_summary <- as.data.frame(coef(summary(fit.week_dentheta_tonic))) 
tonic_dentheta_summary <- tonic_dentheta_summary[2,]

results_adj <- rbind(phasicslope_summary, phasic_dentheta_summary, phasic_snralpha_summary, tonicslope_summary, tonic_dentheta_summary, tonic_snralpha_summary) 
colnames(results_adj)[5] <- "pvalue"
results_adj <- results_adj %>%
  mutate(adj_pvalue = p.adjust(pvalue, method = "fdr"))

## plot ----
ordinary_residuals <- residuals(fit.week_snralpha_phasic) # change model accordingly
coeff_of_interest <- as.numeric(fixef(fit.week_snralpha_phasic)["phasic_snr_alpha_z"])
predictor_values <- as.numeric(model.frame(fit.week_snralpha_phasic)$phasic_snr_alpha_z)
partial_residuals_calculated <- ordinary_residuals + coeff_of_interest * predictor_values
df_points_for_plot <- data.frame(
    x_variable = predictor_values,
    y_partial_residual = partial_residuals_calculated)
df_line <- as.data.frame(eff_phasicsnralpha)

plot_corr <- ggplot(data = df_points_for_plot, aes(x = x_variable, y = y_partial_residual)) +
     # Add partial residual points
     geom_point(aes(color = x_variable), size = 0.5 * 2, shape=1, stroke=0.35) +
     scale_color_gradientn(colors = c("#0072B2", "#8bd5ff", "#008bd9", "#8bd5ff", "#0072B2", "#8bd5ff")) +
  #   scale_color_gradientn(colors = c("#FF7a11","#FFbc87", "#FF9038","#FFa65F", "#FF7a11", "#FFbc87")) +
     # Add the fitted line
     geom_line(data = df_line, aes(x = phasic_snr_alpha_z, y = fit),
               color = "black", linewidth = 1) +
     # Add confidence interval ribbon
     geom_ribbon(data = df_line,
                 aes(x = phasic_snr_alpha_z, y=fit, ymin = lower, ymax = upper),
                 fill = "grey", alpha = 0.3) + # No 'y_partial_residual' should be here or implied
     labs(
       # x = expression("tonic spectral slope (z-scored)"),
       #  x="tonic theta density (z-scored)",
         x="phasic alpha amplitude (z-scored)",
         y = expression("spectral slope change\nNREMpost - NREMpre (z-scored)"),
         title = ""
     ) +
    scale_x_continuous(limits = c(-2, 6), breaks = seq(-2, 6, 2), expand = c(0, NA)) +
    scale_y_continuous(limits = c(-6, 6), breaks = seq(-6, 6, 2), expand = c(0, NA)) +
    theme_prism(base_size = 10, base_fontface="plain", base_line_size=0.2) +
    theme(legend.position = "none")
```

