---
title: "oscillations (periodic components) stats"
output: html_notebook
---

# 1. Import functions
```{r}
library(devtools)
library(lmerTest)
library(lme4)
library(emmeans)
library(tidyverse)
library(broom)
library(kableExtra)
library(ggpubr)
library(ggprism)
```
## Looking at baseline nights only, differences between wake/NREM/REM and phasic/tonic (Fig2, S4, S11) 
```{r}
# load data
df_oscillations <- read_csv("data/for paper/oscillations (periodic)/df_oscillations.csv", show_col_types = FALSE)

# Factorise
cols <- c("participant", "condition", "night", "order", "state", "channel")
df_oscillations <- df_oscillations %>% mutate_at(cols, factor)
factor(df_oscillations$night, order=TRUE,
       levels= c("1", "2", "3", "4", "5", "6", "7", "8"))

```
#1 lmes 
```{r}
df_baseline<- df_oscillations %>%
filter(night == "1") %>%
#  filter(state == "wake" | state == "NREM" | state == "REM")
 filter(state == "phasic" | state=="tonic")

# alpha: IAPF, density, height, abundance -----
fit.baseline_IAPF <- lmer(IAPF ~ state*channel + order + tst + (1|participant), data=df_baseline)
anova.baseline_IAPF  <-  anova(fit.baseline_IAPF )

#res <- residuals(fit.baseline_IAPF)
#hist(res)

fit.baseline_densityalpha <- lmer(densityalpha ~ state*channel + order + tst + (1|participant), data=df_baseline)
anova.baseline_densityalpha  <-  anova(fit.baseline_densityalpha )

fit.baseline_snralpha <- lmer(snralpha ~ state*channel + order + tst + (1|participant), data=df_baseline)
anova.baseline_snralpha  <-  anova(fit.baseline_snralpha )

# theta: ITPF, density, height, abundance ----
fit.baseline_ITPF <- lmer(ITPF ~ state*channel + order + tst + (1|participant), data=df_baseline)
anova.baseline_ITPF  <-  anova(fit.baseline_ITPF )

fit.baseline_densitytheta <- lmer(densitytheta ~ state*channel + order + tst + (1|participant), data=df_baseline)
anova.baseline_densitytheta  <-  anova(fit.baseline_densitytheta )

fit.baseline_snrtheta <- lmer(snrtheta ~ state*channel + order + tst + (1|participant), data=df_baseline)
anova.baseline_snrtheta  <-  anova(fit.baseline_snrtheta)

# estimated means
baseline_IAPF_statechannel_esmmeans <- estimate_means(fit.baseline_IAPF , by = c("state", "channel"))
baseline_densityalpha_statechannel_esmmeans <- estimate_means(fit.baseline_densityalpha , by = c("state", "channel"))
baseline_snralpha_statechannel_esmmeans <- estimate_means(fit.baseline_snralpha , by = c("state", "channel"))

baseline_ITPF_statechannel_esmmeans <- estimate_means(fit.baseline_ITPF , by = c("state", "channel"))
baseline_densitytheta_statechannel_esmmeans <- estimate_means(fit.baseline_densitytheta , by = c("state", "channel"))
baseline_snrtheta_statechannel_esmmeans <- estimate_means(fit.baseline_snrtheta , by = c("state", "channel"))

```
#2 Posthoc 
```{r}
# compare channels for each state -- "simple effects"
pairs(emmeans(fit.baseline_IAPF, ~state:channel, by="channel", p.adjust = "tukey"))
pairs(emmeans(fit.baseline_densityalpha, ~state:channel, by="channel", p.adjust = "tukey"))
pairs(emmeans(fit.baseline_snralpha, ~state:channel, by="channel", p.adjust = "tukey"))
```
#3 Plot
```{r}
# average across nights for visualisation
df_baseline_average <- df_baseline %>% 
  select(!c(3:6)) %>% 
  group_by(participant, state, channel) %>% 
  dplyr::summarise(across(everything(), mean, na.rm=TRUE))
df_baseline_average$state <- factor(df_baseline_average$state, order=TRUE,
       #levels= c("wake", "NREM", "REM")) 
       levels= c("phasic", "tonic"))
df_baseline_average$channel <- factor(df_baseline_average$channel, order=TRUE,
       levels= c("frontal", "central", "parietal", "occipital"))

# wake NREM REM ----
# density theta 
densitytheta_topography <- ggplot(df_baseline_average, aes(x = channel, y = densitytheta, fill = state)) +
geom_violin() +
#colorBlindBlack8  <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
  scale_fill_manual(values = c("wake" = "#F0E442", "REM" = "#CC79A7", "NREM"="#009E73")) + 
#  scale_y_continuous(limits = c(0, 15), breaks = seq(0, 15, 3), expand = c(0, NA)) + # set scales to begin at , intervals of 3 until highest value , expand prevents padding at top and bottom of y axis so it will be in line with x axis
   scale_y_continuous(limits = c(0, 18), breaks = seq(0, 18, 3), expand = c(0, NA)) +
  ylab("density(oscillations/min)") +
  theme_prism(base_size = 9, base_fontface="plain", base_line_size=0.2) +
  theme(legend.position = "none") +
  geom_errorbar(data=subset(baseline_densitytheta_statechannel_esmmeans, state == "wake"), aes(x=channel, y=Mean, ymin=Mean-SE, ymax=Mean+SE), width=0.1, lwd=0.5, position = position_nudge(x = -0.3)) +
  geom_point(data = subset(baseline_densitytheta_statechannel_esmmeans, state == "wake"), aes(x=channel, y=Mean),shape=21, size =1,  position = position_nudge(x = -0.3)) +
    geom_errorbar(data=subset(baseline_densitytheta_statechannel_esmmeans, state == "NREM"), aes(x=channel, y=Mean, ymin=Mean-SE, ymax=Mean+SE), width=0.1, lwd=0.5, position = position_nudge(x = 0)) +
  geom_point(data = subset(baseline_densitytheta_statechannel_esmmeans, state == "NREM"), aes(x=channel, y=Mean),shape=21, size =1,  position = position_nudge(x = 0)) +
      geom_errorbar(data=subset(baseline_densitytheta_statechannel_esmmeans, state == "REM"), aes(x=channel, y=Mean, ymin=Mean-SE, ymax=Mean+SE), width=0.1, lwd=0.5, position = position_nudge(x = 0.3)) +
  geom_point(data = subset(baseline_densitytheta_statechannel_esmmeans, state == "REM"), aes(x=channel, y=Mean),shape=21, size =1,  position = position_nudge(x = 0.3)) 

# phasic tonic ----
densitytheta_topography <- ggplot(df_baseline_average, aes(x = channel, y = densitytheta, fill = state)) +
geom_violin() +
#colorBlindBlack8  <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
   scale_fill_manual(values = c("phasic" = "#0072B2", "tonic" = "#D55E00")) + 
   scale_y_continuous(limits = c(0, 18), breaks = seq(0, 18, 3), expand = c(0, NA)) +
  ylab("density(oscillations/min)") +
  theme_prism(base_size = 9, base_fontface="plain", base_line_size=0.2) +
  theme(legend.position = "none") +
  geom_errorbar(data=subset(baseline_densitytheta_statechannel_esmmeans, state == "phasic"), aes(x=channel, y=Mean, ymin=Mean-SE, ymax=Mean+SE), width=0.1, lwd=0.5, position = position_nudge(x = -0.22)) +
  geom_point(data = subset(baseline_densitytheta_statechannel_esmmeans, state == "phasic"), aes(x=channel, y=Mean),shape=21, size =1,  position = position_nudge(x = -0.22)) +
    geom_errorbar(data=subset(baseline_densitytheta_statechannel_esmmeans, state == "tonic"), aes(x=channel, y=Mean, ymin=Mean-SE, ymax=Mean+SE), width=0.1, lwd=0.5, position = position_nudge(x = 0.22)) +
  geom_point(data = subset(baseline_densitytheta_statechannel_esmmeans, state == "tonic"), aes(x=channel, y=Mean),shape=21, size =1,  position = position_nudge(x = 0.22)) 
```

## Looking at the whole week, changes in phasic and tonic (Fig3, S5)
```{r}
# Load data
df_oscillations_week <- read_csv("data/for paper/oscillations (periodic)/df_oscillations_week.csv", show_col_types = FALSE)

# Factorise
cols <- c("participant", "condition", "night", "order", "state", "channel")
df_oscillations_week <- df_oscillations_week %>% mutate_at(cols, factor)
factor(df_oscillations_week$night, order=TRUE,
       levels= c("1", "2", "3", "4", "5", "6", "7", "8"))
```
#1 lmes 
```{r}
df_oscillations_week %>% df_oscillations_week
  filter(state == "phasic" | state == "tonic") 

# alpha: IAPF, density, amplitude -----
# NB condition not used alone as a fixed effect due to the intention for model to see SE and SR baseline as "one"
fit.q2_IAPF <- lmer(IAPF ~  channel + night*state + night:condition + condition:channel + state:night:condition + order + tst + IAPF_baseline + (1|participant), data=df_oscillations_week)
anova.q2_IAPF  <-  anova(fit.q2_IAPF)

fit.q2_densityalpha <- lmer(densityalpha ~ night + channel + night*state + night:condition +condition:channel + state:night:condition + tst + densityalpha_baseline + order +(1|participant), data=df_oscillations_week)
anova.q2_densityalpha  <-  anova(fit.q2_densityalpha)

fit.q2_snralpha <- lmer(snralpha ~ night + channel + night*state + night:condition + condition:channel + state:night:condition + tst + snralpha_baseline + order +(1|participant), data=df_oscillations_week)
anova.q2_snralpha  <-  anova(fit.q2_snralpha)

# theta: ITPF, density, amplitude ----
fit.q2_ITPF <- lmer(ITPF ~ night + channel + night*state + night:condition + condition:channel + state:night:condition + tst + ITPF_baseline + order +(1|participant), data=df_oscillations_week)
anova.q2_ITPF  <-  anova(fit.q2_ITPF)

fit.q2_densitytheta <- lmer(densitytheta ~ night + channel + night*state + night:condition + condition:channel + state:night:condition + tst + densitytheta_baseline + order +(1|participant), data=df_oscillations_week)
anova.q2_densitytheta  <-  anova(fit.q2_densitytheta)

fit.q2_snrtheta <- lmer(snrtheta ~ night + channel + night*state + night:condition +condition:channel + state:night:condition + tst + snrtheta_baseline + order +(1|participant), data=df_oscillations_week)
anova.q2_snrtheta  <-  anova(fit.q2_snrtheta)

# estimated means
IAPF.esmmeans <- estimate_means(fit.q2_IAPF , by = c( "condition", "state", "night"))
densityalpha.esmmeans <- estimate_means(fit.q2_densityalpha , by = c( "condition", "state", "night"))
snralpha.esmmeans <- estimate_means(fit.q2_snralpha , by = c( "condition",  "state", "night"))

ITPF.esmmeans <- estimate_means(fit.q2_ITPF , by = c( "condition",  "state", "night"))
densitytheta.esmmeans <- estimate_means(fit.q2_densitytheta , by = c( "condition",  "state", "night"))
snrtheta.esmmeans <- estimate_means(fit.q2_snrtheta , by = c( "condition",  "state", "night"))
```
#2 Posthoc 
```{r}
# compare between conditions, for each state and night (in paper)
pairs(emmeans(fit.q2_densitytheta, ~night:state:condition), simple="condition", p.adjust = "tukey")

# compare change from baseline for each state 
contrast(emmeans(fit.q2_densitytheta, ~ night * condition | state), method = "trt.vs.ctrl", ref = 1, p.adjust = "sidak") # change from baseline
```
#3 Plot
```{r}
 IAPF_week <- ggplot(IAPF.esmmeans, aes(x = night, y = Mean, linetype=condition, colour=state, shape=condition, group=condition)) +
     facet_grid(~state) +
 geom_line() +
     geom_errorbar(aes(x=night, y=Mean, ymin=Mean-SE, ymax=Mean+SE,), linetype=1, width=0.4, lwd=0.3, position = position_dodge(0.3)) +
  geom_point(aes(colour=state),fill="white", size=2, position = position_dodge(0.3)) +
  theme_prism(base_size = 10, base_fontface="plain", base_line_size=0.2) +
  scale_y_continuous(limits = c(8, 8.5), breaks = seq(8,8.5,0.1), expand = c(0, NA))+
  scale_x_discrete(labels=c("B", "1", "2", "3", "4", "5", "6", "7")) +
  scale_colour_manual(values = c("phasic" = "#0072B2", "tonic" = "#D55E00")) + 
  xlab("night") +  ylab("peak frequency (Hz)") +
    scale_shape_manual(values = c(16,21)) +
   theme(legend.position="none") 
```

