---
title: "slope stats"
output: html_notebook
---

# Import functions
```{r}
library(devtools)
library(lmerTest)
library(lme4)
library(emmeans)
library(tidyverse)
library(broom)
library(kableExtra)
library(ggpubr)
library(ggprism)
library(modelbased)
library(gghalves)
```

## Looking at baseline nights only, differences between wake/NREM/REM and phasic/tonic (Fig2, S4, S5, S8) 
```{r}
# load data
df_slope <- readRDS("df_slope_27July26.rds")

# Factorise
cols <- c("participant", "condition", "night", "order", "state", "channel")
df_slope <- df_slope %>% mutate_at(cols, factor)
factor(df_slope$night, order=TRUE,
       levels= c("1", "2", "3", "4", "5", "6", "7", "8"))

```
# phasic vs tonic 
# 1. lmes 
```{r}
df_baseline <- df_slope %>%
  filter(night == "1") %>%
   filter(state=="phasic" | state == "tonic") 

fit.baseline_exp1to30 <- lmer(exp1to30 ~ state*channel + order + tst + (1|participant), data=df_baseline)
anova.baseline_exp1to30 <-  anova(fit.baseline_exp1to30)

fit.baseline_exp30to45 <- lmer(exp30to45 ~ state*channel + order + tst + (1|participant), data=df_baseline)
anova.baseline_exp30to45 <-  anova(fit.baseline_exp30to45)

# estimated means
baseline_exp1to30_state_esmmeans <- estimate_means(fit.baseline_exp1to30, by = c("state"))

baseline_exp30to45_statechannel_esmmeans <- estimate_means(fit.baseline_exp30to45, by = c("state", "channel"))
baseline_exp30to45_state_esmmeans <- estimate_means(fit.baseline_exp30to45, by = c("state"))

# posthoc 
# compare between states
pairs(emmeans(fit.baseline_exp1to30, ~state, p.adjust = "tukey"))
pairs(emmeans(fit.baseline_exp30to45, ~state, p.adjust = "tukey"))

# compare channels for each state
pairs(emmeans(fit.baseline_exp30to45, ~state:channel, by="channel", p.adjust = "tukey"))
```
#2 Plot
```{r}
library(gghalves) # for geom half violin

# Plot state ----
# average across channel and nights for visualisation
df_baseline_average <- df_baseline %>% 
 dplyr::select(c(1,2,8,9,10,11)) %>% 
  group_by(participant, state) %>% 
  dplyr::summarise(across(everything(), mean, na.rm=TRUE))

# exponent 1-30Hz (Fig S3) ----
exp1to30_base <- ggplot(df_baseline_average, aes(x = state, y = exp1to30, fill = state)) +
  # Left half violin for phasic
  geom_half_violin(data = subset(df_baseline_average, state == "phasic"),side = "l",  # <-- flip to left
 alpha = 0.8, trim = FALSE, position = position_nudge(x = -0.1)) +
# Right half violin for tonic
  geom_half_violin(data = subset(df_baseline_average, state == "tonic"),side = "r", alpha = 0.8, trim = FALSE, position = position_nudge(x = 0.1)) +
# join same participants with line across state
   geom_line(aes(group = participant), colour = "black", linewidth = 0.3, alpha = 0.2, position = position_jitter(width = 0.05, seed = 123)) +
  geom_point(aes(shape = state, colour=state), size=1, position = position_jitter(width = 0.05, seed = 123)) +
#colorBlindBlack8  <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
  scale_fill_manual(values = c("phasic" = "#0072B2", "tonic" = "#D55E00")) + 
  scale_colour_manual(values = c("phasic" = "#0072B2", "tonic" = "#D55E00")) + 
  scale_shape_manual(values = c(21,21)) +
  scale_y_continuous(limits = c(-2.4, -1), breaks = seq(-2.4, -1, 0.2), expand = c(0, NA)) + # set scales to begin at , intervals of 3 until highest value , expand prevents padding at top and bottom of y axis so it will be in line with x axis
 ylab(expression("spectral slope 1-30 Hz "~(mu*V^2/Hz))) +
  theme_prism(base_size = 11, base_fontface="plain", base_line_size=0.2) +
  theme(legend.position = "none")

  # add error bar and mean for phasic (esmmeans)
exp1to30_base <- exp1to30_base +
   geom_errorbar(data = subset(baseline_exp1to30_state_esmmeans, state == "phasic"), aes(x=state, y=Mean, ymin=Mean-SE, ymax=Mean+SE), width=0.1, lwd=0.5, position = position_nudge(x = -0.2)) +
    geom_point(data = subset(baseline_exp1to30_state_esmmeans, state == "phasic"), aes(x=state, y=Mean, shape=state, colour=state), fill="#0072B2", colour="black", size =2,  position = position_nudge(x = -0.2)) +
   # add error bar and mean for tonic (esmmeans)
    geom_errorbar(data = subset(baseline_exp1to30_state_esmmeans, state == "tonic"), aes(x=state, y=Mean, ymin=Mean-SE, ymax=Mean+SE), width=0.1, lwd=0.5, position = position_nudge(x = 0.2)) +
    geom_point(data = subset(baseline_exp1to30_state_esmmeans, state == "tonic"), aes(x=state, y=Mean, shape=state, colour=state),colour="black", size =2,  position = position_nudge(x = 0.2))  +
 # geom_line(data = baseline_ITPF_state_esmmeans, aes(x=state, y=Mean, group=1), colour = "black", linewidth = 1) +
  scale_x_discrete(name = NULL)  

#ggsave("figure/figS3/exp1to30_REM.svg", plot=exp1to30_base, width=3, height=4)

# exponent 30-45Hz (Fig 2c) ----
exp30to45_base <- ggplot(df_baseline_average, aes(x = state, y = exp30to45, fill = state)) +
  # Left half violin for phasic
  geom_half_violin(data = subset(df_baseline_average, state == "phasic"),side = "l",  # <-- flip to left
 alpha = 0.8, trim = FALSE, position = position_nudge(x = -0.1)) +
# Right half violin for tonic
  geom_half_violin(data = subset(df_baseline_average, state == "tonic"),side = "r", alpha = 0.8, trim = FALSE, position = position_nudge(x = 0.1)) +
# join same participants with line across state
   geom_line(aes(group = participant), colour = "black", linewidth = 0.3, alpha = 0.2, position = position_jitter(width = 0.05, seed = 123)) +
  geom_point(aes(shape = state, colour=state), size=1, position = position_jitter(width = 0.05, seed = 123)) +
#colorBlindBlack8  <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
  scale_fill_manual(values = c("phasic" = "#0072B2", "tonic" = "#D55E00")) + 
  scale_colour_manual(values = c("phasic" = "#0072B2", "tonic" = "#D55E00")) + 
  scale_shape_manual(values = c(21,21)) +
  scale_y_continuous(limits = c(-6, -1.5), breaks = seq(-6, -1.5, 0.5), expand = c(0, NA)) + # set scales to begin at , intervals of 3 until highest value , expand prevents padding at top and bottom of y axis so it will be in line with x axis
  ylab(expression("spectral slope 30-45 Hz "~(mu*V^2/Hz))) +
  theme_prism(base_size = 11, base_fontface="plain", base_line_size=0.2) +
  theme(legend.position = "none")

  # add error bar and mean for phasic (esmmeans)
exp30to45_base <- exp30to45_base +
   geom_errorbar(data = subset(baseline_exp30to45_state_esmmeans, state == "phasic"), aes(x=state, y=Mean, ymin=Mean-SE, ymax=Mean+SE), width=0.1, lwd=0.5, position = position_nudge(x = -0.2)) +
    geom_point(data = subset(baseline_exp30to45_state_esmmeans, state == "phasic"), aes(x=state, y=Mean, shape=state, colour=state), fill="#0072B2", colour="black", size =2,  position = position_nudge(x = -0.2)) +
   # add error bar and mean for tonic (esmmeans)
    geom_errorbar(data = subset(baseline_exp30to45_state_esmmeans, state == "tonic"), aes(x=state, y=Mean, ymin=Mean-SE, ymax=Mean+SE), width=0.1, lwd=0.5, position = position_nudge(x = 0.2)) +
    geom_point(data = subset(baseline_exp30to45_state_esmmeans, state == "tonic"), aes(x=state, y=Mean, shape=state, colour=state),colour="black", size =2,  position = position_nudge(x = 0.2))  +
 # geom_line(data = baseline_ITPF_state_esmmeans, aes(x=state, y=Mean, group=1), colour = "black", linewidth = 1) +
  scale_x_discrete(name = NULL)  

#ggsave("figure/fig2/exp30to45_REM.svg", plot=exp30to45_base, width=3, height=4)

# Plot state channel ----
# average across nights for visualisation
df_baseline_average <- df_baseline %>% 
  dplyr::select(!c(3:6)) %>% 
  group_by(participant, state, channel) %>% 
  dplyr::summarise(across(everything(), mean, na.rm=TRUE))
df_baseline_average$channel <- factor(df_baseline_average$channel, order=TRUE,
       levels= c("frontal", "central", "parietal", "occipital"))
df_baseline_average$state <- factor(df_baseline_average$state, order=TRUE,
      levels= c("phasic", "tonic"))

# exponent 30-45Hz (Fig S4) ----
exp30to45_topography <- ggplot(df_baseline_average, aes(x = channel, y = exp30to45, fill = state)) +
geom_violin() +
#colorBlindBlack8  <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
 scale_fill_manual(values = c("phasic" = "#0072B2", "tonic" = "#D55E00")) + 
    scale_y_continuous(limits = c(-7, 0), breaks = seq(-7, 0, 1), expand = c(0, NA)) + # set scales to begin at , intervals of 3 until highest value , expand prevents padding at top and bottom of y axis so it will be in line with x axis
  ylab(expression("spectral slope 30-45 Hz "~(mu*V^2/Hz))) +
  theme_prism(base_size = 9, base_fontface="plain", base_line_size=0.2) +
  theme(legend.position = "none") +
  geom_errorbar(data=subset(baseline_exp30to45_statechannel_esmmeans, state == "phasic"), aes(x=channel, y=Mean, ymin=Mean-SE, ymax=Mean+SE), width=0.1, lwd=0.5, position = position_nudge(x = -0.22)) +
  geom_point(data = subset(baseline_exp30to45_statechannel_esmmeans, state == "phasic"), aes(x=channel, y=Mean),shape=21, size =1,  position = position_nudge(x = -0.22)) +
    geom_errorbar(data=subset(baseline_exp30to45_statechannel_esmmeans, state == "tonic"), aes(x=channel, y=Mean, ymin=Mean-SE, ymax=Mean+SE), width=0.1, lwd=0.5, position = position_nudge(x = 0.22)) +
  geom_point(data = subset(baseline_exp30to45_statechannel_esmmeans, state == "tonic"), aes(x=channel, y=Mean),shape=21, size =1,  position = position_nudge(x = 0.22)) 


#ggsave("figure/figS4/exp30to45_topography_phasictonic.svg", plot=exp30to45_topography, width=4, height=3)

```
# wake vs NREM vs REM
# 1. lmes 
```{r}
rm(list = ls()[-match("df_slope", ls())])

df_baseline <- df_slope %>%
  filter(night == "1") %>%
  filter(state == "wake" | state == "NREM" | state == "REM")

fit.baseline_exp30to45 <- lmer(exp30to45 ~ state*channel + order + tst + (1|participant), data=df_baseline)
anova.baseline_exp30to45 <-  anova(fit.baseline_exp30to45)

# estimated means
baseline_exp30to45_statechannel_esmmeans <- estimate_means(fit.baseline_exp30to45, by = c("state", "channel"))

# posthoc 
# compare channels for each state
pairs(emmeans(fit.baseline_exp30to45, ~state:channel, by="channel", p.adjust = "tukey"))
```
# Plot state channel 
```{r}
# average across nights for visualisation
df_baseline_average <- df_baseline %>% 
  dplyr::select(!c(3:6)) %>% 
  group_by(participant, state, channel) %>% 
  dplyr::summarise(across(everything(), mean, na.rm=TRUE))
df_baseline_average$channel <- factor(df_baseline_average$channel, order=TRUE,
       levels= c("frontal", "central", "parietal", "occipital"))
df_baseline_average$state <- factor(df_baseline_average$state, order=TRUE,
      levels= c("wake", "NREM", "REM"))

## wake NREM REM ----
# exponent 30-45Hz (Fig S4)
exp30to45_topography <- ggplot(df_baseline_average, aes(x = channel, y = exp30to45, fill = state)) +
geom_violin() +
#colorBlindBlack8  <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
  scale_fill_manual(values = c("wake" = "#F0E442", "REM" = "#CC79A7", "NREM"="#009E73")) + 
    scale_y_continuous(limits = c(-7, 0), breaks = seq(-7, 0, 1), expand = c(0, NA)) + # set scales to begin at , intervals of 3 until highest value , expand prevents padding at top and bottom of y axis so it will be in line with x axis
  ylab(expression("spectral slope 30-45 Hz "~(mu*V^2/Hz))) +
  theme_prism(base_size = 9, base_fontface="plain", base_line_size=0.2) +
  theme(legend.position = "none") +
  geom_errorbar(data=subset(baseline_exp30to45_statechannel_esmmeans, state == "wake"), aes(x=channel, y=Mean, ymin=Mean-SE, ymax=Mean+SE), width=0.1, lwd=0.5, position = position_nudge(x = -0.3)) +
  geom_point(data = subset(baseline_exp30to45_statechannel_esmmeans, state == "wake"), aes(x=channel, y=Mean),shape=21, size =1,  position = position_nudge(x = -0.3)) +
    geom_errorbar(data=subset(baseline_exp30to45_statechannel_esmmeans, state == "NREM"), aes(x=channel, y=Mean, ymin=Mean-SE, ymax=Mean+SE), width=0.1, lwd=0.5, position = position_nudge(x = 0)) +
  geom_point(data = subset(baseline_exp30to45_statechannel_esmmeans, state == "NREM"), aes(x=channel, y=Mean),shape=21, size =1,  position = position_nudge(x = 0)) +
      geom_errorbar(data=subset(baseline_exp30to45_statechannel_esmmeans, state == "REM"), aes(x=channel, y=Mean, ymin=Mean-SE, ymax=Mean+SE), width=0.1, lwd=0.5, position = position_nudge(x = 0.3)) +
  geom_point(data = subset(baseline_exp30to45_statechannel_esmmeans, state == "REM"), aes(x=channel, y=Mean),shape=21, size =1,  position = position_nudge(x = 0.3)) 

#ggsave("figure/figS4/exp30to45_topography_allstates.svg", plot=exp30to45_topography, width=5, height=3)

```
## Looking at the whole week, changes in phasic and tonic (Fig3)
```{r}
# clear global environment 
rm(list = ls())

# load data
df_slope_week <- readRDS("df_slope_week_27July26.rds")

# Factorise
cols <- c("participant", "condition", "night", "order", "state", "channel")
df_slope_week <- df_slope_week %>% mutate_at(cols, factor)
factor(df_slope_week$night, order=TRUE,
       levels= c("1", "2", "3", "4", "5", "6", "7", "8"))

```
# 1. lmes
```{r}
df_REM <- df_slope_week %>%
  filter(state == "phasic" | state == "tonic")

fit.REM_exp30to45 <-  lmer(exp30to45 ~ channel + night*state + night:condition + condition:channel + state:night:condition + order +tst + exp30to45_baseline + (1|participant), data=df_REM)
anova.REM_exp30to45 <- anova(fit.REM_exp30to45)

# estimated means
REM_exp30to45.esmmeans <- estimate_means(fit.REM_exp30to45 , by = c("state", "night", "condition"))

# F-test for night × condition WITHIN each state
emm <- emmeans(fit.REM_exp30to45, ~ night * condition | state)
joint_tests(emm, by = "state")

# posthoc between conditions for each night within each state
pairs(emmeans(fit.REM_exp30to45, ~night:state:condition,
              pbkrtest.limit = 3632,
              lmerTest.limit = 3632),
      simple = "condition",
      adjust = "tukey",
      lmer.df = "kenward-roger")
```
#2. Plot
```{r}
#exp 30 to 45Hz 
exp30to45_REM_week <- ggplot(REM_exp30to45.esmmeans, aes(x = night, y = Mean, colour=state, shape=condition, group=condition)) +
     facet_grid(~state) +
 geom_line() +
     geom_errorbar(aes(x=night, y=Mean, ymin=Mean-SE, ymax=Mean+SE,), linetype=1, width=0.4, lwd=0.3, position = position_dodge(0.3)) +
  geom_point(aes(colour=state),fill="white", size=2, position = position_dodge(0.3)) +
  theme_prism(base_size = 10, base_fontface="plain", base_line_size=0.2) +
  scale_y_continuous(limits = c(-3.8, -3.4), breaks = seq(-3.8, -3.4, 0.08), expand = c(0, NA))+
  scale_x_discrete(labels=c("B", "1", "2", "3", "4", "5", "6", "7")) +
  scale_colour_manual(values = c("phasic" = "#0072B2", "tonic" = "#D55E00")) + 
    scale_shape_manual(values = c(16,21)) +
  ylab(expression("spectral slope 30-45 Hz "~(mu*V^2/Hz))) +
  theme(legend.position="none") 


#exp 30 to 45Hz - with violin and individual points
exp30to45_REM_week <-    ggplot(REM_exp30to45.esmmeans, aes(x = night, y = Mean, group = condition, shape = condition, colour = state)) +
    scale_shape_manual(values = c(16, 21)) +
    facet_grid(~state) +
   geom_violin(data = subset(df_REM, condition == "SE"), aes(x = night, y = exp30to45, group = interaction(night, condition), colour=state), inherit.aes = FALSE, position = position_nudge(-0.15),width = 0.4,alpha = 0.1,linewidth = 0.1) +
    geom_violin(data = subset(df_REM, condition == "SR"), aes(x = night, y = exp30to45, group = interaction(night, condition), colour=state), inherit.aes = FALSE, position = position_nudge(0.15),width = 0.4,alpha = 0.1,linewidth = 0.1) +
    geom_point(data = subset(df_REM, condition == "SE"),
               aes(x = night, y = exp30to45, group = interaction(night, condition), colour=state),
               shape = 16, inherit.aes = FALSE,
               position = position_nudge(x = -0.15),
               alpha = 0.3, size = 0.3) +
    geom_point(data = subset(df_REM, condition == "SR"),
               aes(x = night, y = exp30to45, group = interaction(night, condition), colour=state),
               shape = 21, fill = "white", inherit.aes = FALSE,
               position = position_nudge(x = 0.15),
               alpha = 0.2, size = 0.3) +
    geom_line(colour="black", lwd=0.1) +
   geom_errorbar(data = subset(REM_exp30to45.esmmeans, condition == "SE"),
                  aes(x = night, y = Mean, ymin = Mean - SE, ymax = Mean + SE),
                  width = 0.4, lwd = 0.1, position = position_nudge(-0.15)) +
    geom_errorbar(data = subset(REM_exp30to45.esmmeans, condition == "SR"),
                  aes(x = night, y = Mean, ymin = Mean - SE, ymax = Mean + SE),
                  width = 0.4, lwd = 0.1, position = position_nudge(0.15)) +
    geom_point(data = subset(REM_exp30to45.esmmeans, condition == "SE"),
               aes(shape = condition),
               position = position_nudge(-0.15), size = 0.8,stroke = 0.3, colour="black", fill="black") +
    geom_point(data = subset(REM_exp30to45.esmmeans, condition == "SR"),
               aes(shape = condition),
               position = position_nudge(0.15), size = 0.8,stroke = 0.3, colour="black", fill="white") +
    labs(x = "Night", y = expression("spectral slope 1-30 Hz "~(mu*V^2/Hz))) +
    scale_colour_manual(values = c("phasic" = "#0072B2", "tonic" = "#D55E00")) + 
    scale_y_continuous(limits = c(-8, -1), breaks = seq(-8, -1, 0.5), expand = c(0, NA)) +
    scale_x_discrete(labels = c("B", "1", "2", "3", "4", "5", "6", "7")) +
    theme_prism(base_size = 9, base_fontface = "plain", base_line_size = 0.2) +
    theme(legend.position = "none")

ggsave("figure/fig3/exp30to45_REM_week.svg", plot=exp30to45_REM_week, width=5, height=3) 

```

